<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_P5zt4BqPEfC8TeDcwO75Gw" name="Harry Assignment " bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_P5zt4RqPEfC8TeDcwO75Gw" name="MoneyBags">
      <elements xmi:type="process:Lane" xmi:id="_P5zt4hqPEfC8TeDcwO75Gw" name="Client" actor="_P5zt-xqPEfC8TeDcwO75Gw">
        <elements xmi:type="process:StartEvent" xmi:id="_P5zt4xqPEfC8TeDcwO75Gw" name="Client Onboarding" outgoing="_Ba2UgBqQEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_P5zt5BqPEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_P5zt5RqPEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_P5zt5hqPEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_71zXkBqPEfC8TeDcwO75Gw" name="Fill out Sign-up form" outgoing="_XLeYIBqkEfC8TeDcwO75Gw" incoming="_Ba2UgBqQEfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_71zXkhqPEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_71zXkRqPEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_71zXkxqPEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_71zXlBqPEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_71zXlRqPEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_71zXlhqPEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_71zXmBqPEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_71zXlxqPEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_71zXmhqPEfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60wCA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_71zXmRqPEfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_71zXnBqPEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kwYpQBqREfC8TeDcwO75Gw" name="Upload Proof of Identity" outgoing="__-EikBqREfC8TeDcwO75Gw" incoming="_SmW1oB2uEfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kwYpQhqREfC8TeDcwO75Gw" name="Upload Proof of Identity" content="Upload Proof of Identity" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kwYpQRqREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kwYpQxqREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kwYpRBqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kwYpRRqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kwYpRhqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kwYpSBqREfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kwYpRxqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kwZQURqREfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60wSA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kwZQUBqREfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kwZQUxqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_x_yp0BqREfC8TeDcwO75Gw" name="Provide/ Request HIN" outgoing="_JkxhoBqTEfC8TeDcwO75Gw" incoming="__-EikBqREfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x_yp0hqREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x_yp0RqREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x_yp0xqREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x_yp1BqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x_yp1RqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x_yp1hqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x_zQ4RqREfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x_zQ4BqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_x_zQ4xqREfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60wiA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_x_zQ4hqREfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_x_zQ5RqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_FneloBqTEfC8TeDcwO75Gw" name="Deposit Funds" outgoing="_eYGcwB5bEfC_E-Cc_pi2TQ" incoming="_JkxhoBqTEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FnelohqTEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FneloRqTEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FneloxqTEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FnelpBqTEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FnelpRqTEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FnelphqTEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FnelqBqTEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FnelpxqTEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_V_npABqkEfC8TeDcwO75Gw" name="Signup Source" outgoing="_iyjI8BqkEfC8TeDcwO75Gw _SDPhgB2uEfC8TeDcwO75Gw" incoming="_XLeYIBqkEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_V_oQERqkEfC8TeDcwO75Gw" name="Signup Source" content="Signup Source" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_V_oQEBqkEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_V_oQEhqkEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_NFLFAB2uEfC8TeDcwO75Gw" name="Signup Complete" outgoing="_SmW1oB2uEfC8TeDcwO75Gw" incoming="_PKhn8B2uEfC8TeDcwO75Gw _SDPhgB2uEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NFLFAh2uEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NFLFAR2uEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NFLFAx2uEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_R0hSUB5ZEfC_E-Cc_pi2TQ" name="Request Transfer of Instruments to Existing Broker" outgoing="_uHu-YB5bEfC_E-Cc_pi2TQ" incoming="_vZkZsB5bEfC_E-Cc_pi2TQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R0sRcR5ZEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R0sRcB5ZEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R0sRch5ZEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_R0sRcx5ZEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_R0sRdB5ZEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_R0sRdR5ZEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_R0sRdx5ZEfC_E-Cc_pi2TQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_R0sRdh5ZEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_TsDw0B5bEfC_E-Cc_pi2TQ" name="Instrument Transfer" outgoing="_vZkZsB5bEfC_E-Cc_pi2TQ _xBeysB5bEfC_E-Cc_pi2TQ" incoming="_3g67UB5bEfC_E-Cc_pi2TQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TsDw0h5bEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TsDw0R5bEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TsDw0x5bEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_m_oTQB5bEfC_E-Cc_pi2TQ" name="Transfer Request Complete" outgoing="_7tiswB5bEfC_E-Cc_pi2TQ" incoming="_uHu-YB5bEfC_E-Cc_pi2TQ _xBeysB5bEfC_E-Cc_pi2TQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_m_o6UR5bEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_m_o6UB5bEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_m_o6Uh5bEfC_E-Cc_pi2TQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_Zhp50B_dEfC_E-Cc_pi2TQ" name="Receive confirmation email" outgoing="_Ndw9cB2pEfC8TeDcwO75Gw" incoming="_f6kewBzfEfC8TeDcwO75Gw" event="Confirmation of Trading Enablement">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KgjNMhzfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KgjNMRzfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KgjNMxzfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KgjNNBzfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KgjNNRzfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KgjNNhzfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KgjNOBzfEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KgjNNxzfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ViueMBqPEfC8TeDcwO75Gw" name="Employee" actor="_P5zt-xqPEfC8TeDcwO75Gw">
        <elements xmi:type="process:Activity" xmi:id="_TUkLQBqUEfC8TeDcwO75Gw" name="Create Booking Account" outgoing="_VTxYABqWEfC8TeDcwO75Gw" incoming="_hlPpEB2pEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TUkyURqUEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TUkyUBqUEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TUkyUhqUEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TUkyUxqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TUkyVBqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TUkyVRqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TUkyVxqUEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TUkyVhqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_Q123sBqVEfC8TeDcwO75Gw" name="Input &amp; send KYC details to Ballarat " outgoing="_X1hYgBqVEfC8TeDcwO75Gw" incoming="_eYGcwB5bEfC_E-Cc_pi2TQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q13ewRqVEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q13ewBqVEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Q13ewhqVEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Q13ewxqVEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Q13exBqVEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Q13exRqVEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Q13exxqVEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Q13exhqVEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_9-XAEB_gEfC_E-Cc_pi2TQ" name="KYC Details">
            <correlation xmi:type="process:Correlation" xmi:id="_9-XAER_gEfC_E-Cc_pi2TQ">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_9-XAEh_gEfC_E-Cc_pi2TQ"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_9-XAEx_gEfC_E-Cc_pi2TQ" name="kycProfileBusinessObject" content="kycProfileBusinessObject" type="TYPE_VARIABLE" returnType="com.company.model.KYCprofile" returnTypeFixed="true">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_SB3KoB_hEfC_E-Cc_pi2TQ" name="kycProfileBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.KYCprofile"/>
            </targetProcessExpression>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_9-XAFB_gEfC_E-Cc_pi2TQ" name="Proof of Identity Documents" content="Proof of Identity Documents" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_9-XAFR_gEfC_E-Cc_pi2TQ">
              <expressions xmi:type="expression:ListExpression" xmi:id="_9-XAFh_gEfC_E-Cc_pi2TQ">
                <expressions xmi:type="expression:Expression" xmi:id="_9-XAFx_gEfC_E-Cc_pi2TQ" content="" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_9-XAGB_gEfC_E-Cc_pi2TQ" content=""/>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_S0ocEBqWEfC8TeDcwO75Gw" name="Wealth &lt; 1M Dollars" outgoing="_1hhR4BqWEfC8TeDcwO75Gw _ww-PkB2tEfC8TeDcwO75Gw" incoming="_VTxYABqWEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_S0pDIRqWEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_S0pDIBqWEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_S0pDIhqWEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_tViu8BqWEfC8TeDcwO75Gw" name="Arrange face to face meeting" outgoing="_zUJ-AB2tEfC8TeDcwO75Gw" incoming="_1hhR4BqWEfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tViu8hqWEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tViu8RqWEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tViu8xqWEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tViu9BqWEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tViu9RqWEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tViu9hqWEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tViu-BqWEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tViu9xqWEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_tViu-hqWEfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60wyA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_tViu-RqWEfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_tViu_BqWEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_UhPXYBzREfC8TeDcwO75Gw" name="Create Client in Slipstream" outgoing="_vBGhYBzREfC8TeDcwO75Gw" incoming="_7tiswB5bEfC_E-Cc_pi2TQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UhP-cRzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UhP-cBzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UhP-chzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UhP-cxzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UhP-dBzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UhP-dRzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UhP-dxzREfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UhP-dhzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2nLh8BzREfC8TeDcwO75Gw" name="Send Confirmatin email to Client" outgoing="_f6kewBzfEfC8TeDcwO75Gw" incoming="_5iSBIBzREfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2nLh8hzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2nLh8RzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2nLh8xzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2nLh9BzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2nLh9RzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2nLh9hzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2nLh-BzREfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2nLh9xzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_2nLh-hzREfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60xCA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_2nLh-RzREfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_2nLh_BzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_fC1JABzgEfC8TeDcwO75Gw" name="Process > 30 days" outgoing="_4_m-oBzhEfC8TeDcwO75Gw _DCVV4BzkEfC8TeDcwO75Gw" incoming="_Ndw9cB2pEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fC1wERzgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fC1wEBzgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fC1wEhzgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_jYNoAB5YEfC_E-Cc_pi2TQ" name="30 Days 00:00:00" content="2592000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Bq5o4BzkEfC8TeDcwO75Gw" name="End of Process" incoming="_DCVV4BzkEfC8TeDcwO75Gw _qfMoIB2wEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Bq6P8RzkEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Bq6P8BzkEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Bq6P8hzkEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_u5phkB2tEfC8TeDcwO75Gw" name="Proceed" outgoing="_0goYMB2tEfC8TeDcwO75Gw" incoming="_ww-PkB2tEfC8TeDcwO75Gw _zUJ-AB2tEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_u5qIoR2tEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_u5qIoB2tEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_u5qIoh2tEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_aM8-IB2vEfC8TeDcwO75Gw" name="Enable for Trading" outgoing="_5iSBIBzREfC8TeDcwO75Gw" incoming="_vBGhYBzREfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_i8SEohzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_i8SEoRzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_i8SEoxzREfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_i8SEpBzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_i8SEpRzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_i8SEphzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_i8SEqBzREfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_i8SEpxzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_aM9lNh2vEfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60xSA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_aM9lNR2vEfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_aM9lOB2vEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_V0VyoBqPEfC8TeDcwO75Gw" name="MegaSalesSmasherRobot">
        <elements xmi:type="process:ServiceTask" xmi:id="_PlaGABqhEfC8TeDcwO75Gw" name="Record Signing Bonus " outgoing="_PKhn8B2uEfC8TeDcwO75Gw" incoming="_iyjI8BqkEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PlaGAhqhEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PlaGARqhEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PlatEBqhEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PlatERqhEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PlatEhqhEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PlatExqhEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PlatFRqhEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PlatFBqhEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_WKzK0BqPEfC8TeDcwO75Gw" name="Ballarat" actor="_P5zt-xqPEfC8TeDcwO75Gw">
        <elements xmi:type="process:ServiceTask" xmi:id="_snSsYBqXEfC8TeDcwO75Gw" name="Run Risk Checks" outgoing="_Rli5IBqeEfC8TeDcwO75Gw" incoming="_0goYMB2tEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_snTTcRqXEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_snTTcBqXEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_snTTchqXEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_snTTcxqXEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_snTTdBqXEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_snTTdRqXEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_snTTdxqXEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_snTTdhqXEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_OVePgBqeEfC8TeDcwO75Gw" name="Save KYC Record for Risk Review" outgoing="_jvwKIBzrEfC8TeDcwO75Gw" incoming="_Rli5IBqeEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OVe2kRqeEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OVe2kBqeEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OVe2khqeEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OVe2kxqeEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OVe2lBqeEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OVe2lRqeEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OVe2lxqeEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OVe2lhqeEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_vX67IB_gEfC_E-Cc_pi2TQ" name="Receive Proof of Identity documents" outgoing="_hlPpEB2pEfC8TeDcwO75Gw" incoming="_X1hYgBqVEfC8TeDcwO75Gw" event="Proof of Identity Documents">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pDbEYRqUEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pDbEYBqUEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pDbEYhqUEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pDbEYxqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pDbEZBqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pDbEZRqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pDbEZxqUEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pDbEZhqUEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_WfEKoBqPEfC8TeDcwO75Gw" name="KYC Risk Team" actor="_OELTkB5hEfC_E-Cc_pi2TQ">
        <elements xmi:type="process:Task" xmi:id="_ROq0wBqfEfC8TeDcwO75Gw" name="Perform KYC Assesment" outgoing="_fm9wABqfEfC8TeDcwO75Gw" incoming="_jvwKIBzrEfC8TeDcwO75Gw" actor="_OELTkB5hEfC_E-Cc_pi2TQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ROrb0RqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ROrb0BqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ROrb0hqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ROrb0xqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ROrb1BqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ROrb1RqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ROrb1xqfEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ROrb1hqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ROrb2RqfEfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60xiA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ROrb2BqfEfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ROrb2xqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_btNQMBqfEfC8TeDcwO75Gw" name="Approve Client?" outgoing="_gIAAgBqfEfC8TeDcwO75Gw _pr2VUBqfEfC8TeDcwO75Gw" incoming="_fm9wABqfEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_btNQMhqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_btNQMRqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_btNQMxqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_duOswBqfEfC8TeDcwO75Gw" name="Client Rejected" incoming="_gIAAgBqfEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_duPT0RqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_duPT0BqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_duPT0hqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_mSP8QBqfEfC8TeDcwO75Gw" name="Set Daily Transaction Limit" outgoing="_gtgr4BqgEfC8TeDcwO75Gw" incoming="_pr2VUBqfEfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mSP8QhqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mSP8QRqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mSP8QxqfEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mSRKYBqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mSRKYRqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mSRKYhqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mSRKZBqfEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mSRKYxqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mSRKZhqfEfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60xyA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mSRKZRqfEfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mSRKaBqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_d_MEcBqgEfC8TeDcwO75Gw" name="Limit &lt; Available funds" outgoing="_mOqAQBqgEfC8TeDcwO75Gw _oacc0BzZEfC8TeDcwO75Gw" incoming="_gtgr4BqgEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d_MEchqgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d_MEcRqgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d_MrgBqgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kOCMUBqgEfC8TeDcwO75Gw" name="Re-review Transaction Limit" outgoing="_8tkkgBzpEfC8TeDcwO75Gw" incoming="_mOqAQBqgEfC8TeDcwO75Gw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kOCzYRqgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kOCzYBqgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kOCzYhqgEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kOCzYxqgEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kOCzZBqgEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kOCzZRqgEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kOCzZxqgEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kOCzZhqgEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kOCzaRqgEfC8TeDcwO75Gw">
            <targetForm xmi:type="expression:Expression" xmi:id="_iF60yCA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kOCzaBqgEfC8TeDcwO75Gw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kOCzaxqgEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_6-6qUBzpEfC8TeDcwO75Gw" name="Client Rejected by KYC Risk Team" incoming="_8tkkgBzpEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6-6qUhzpEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6-6qURzpEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6-6qUxzpEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_M_e94BqnEfC8TeDcwO75Gw" name="CHESS">
        <elements xmi:type="process:XORGateway" xmi:id="_WYMZsBqnEfC8TeDcwO75Gw" name="Client HIN Check" outgoing="_l6yk4BqnEfC8TeDcwO75Gw _Kg9mcBzrEfC8TeDcwO75Gw" incoming="_oacc0BzZEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WYNn0RqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WYNn0BqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WYNn0hqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_kZNdYBqnEfC8TeDcwO75Gw" name="Validate Provided HIN" outgoing="_S0sXMBzrEfC8TeDcwO75Gw" incoming="_l6yk4BqnEfC8TeDcwO75Gw _MytmoBzrEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kZOEcRqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kZOEcBqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kZOEchqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kZOEcxqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kZOEdBqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kZOEdRqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kZOEdxqnEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kZOEdhqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_s-U5EBqnEfC8TeDcwO75Gw" name="Confirm &amp; Store HIN" outgoing="_3g67UB5bEfC_E-Cc_pi2TQ" incoming="_S0sXMBzrEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s-VgIRqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s-VgIBqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s-VgIhqnEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s-VgIxqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s-VgJBqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s-VgJRqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s-VgJxqnEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s-VgJhqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_F4BscBzrEfC8TeDcwO75Gw" name="HIN Received within 30 days" outgoing="_MytmoBzrEfC8TeDcwO75Gw _P3iCgBzrEfC8TeDcwO75Gw" incoming="_Kg9mcBzrEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F4C6kRzrEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F4C6kBzrEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F4C6khzrEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_6gEUYB5YEfC_E-Cc_pi2TQ" name="30 Days 00:00:00" content="2592000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OXnu8BzrEfC8TeDcwO75Gw" name="Close Account" incoming="_P3iCgBzrEfC8TeDcwO75Gw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OXoWARzrEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OXoWABzrEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OXoWAhzrEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_fpyNwBqPEfC8TeDcwO75Gw" name="Head of Sales &amp; Ops">
        <elements xmi:type="process:ReceiveTask" xmi:id="_ejLVYBzcEfC8TeDcwO75Gw" name="Receive 30-day delay alert" outgoing="_qfMoIB2wEfC8TeDcwO75Gw" incoming="_4_m-oBzhEfC8TeDcwO75Gw" event="30-Day Delay Alert">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ejLVYhzcEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ejLVYRzcEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ejLVYxzcEfC8TeDcwO75Gw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ejLVZBzcEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ejLVZRzcEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ejLVZhzcEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ejLVaBzcEfC8TeDcwO75Gw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ejLVZxzcEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_XGJxwB5eEfC_E-Cc_pi2TQ" name="clientBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.Client">
        <defaultValue xmi:type="expression:Expression" xmi:id="_XGJxwR5eEfC_E-Cc_pi2TQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_buTBkB5eEfC_E-Cc_pi2TQ" name="faceToFaceMeetingBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.FacetoFaceMeeting">
        <defaultValue xmi:type="expression:Expression" xmi:id="_buTBkR5eEfC_E-Cc_pi2TQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_iH62EB5eEfC_E-Cc_pi2TQ" name="instrumentTransferBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.InstrumentTransfer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_iH62ER5eEfC_E-Cc_pi2TQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_lhGYYB5eEfC_E-Cc_pi2TQ" name="kycProfileBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.KYCprofile">
        <defaultValue xmi:type="expression:Expression" xmi:id="_lhGYYR5eEfC_E-Cc_pi2TQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_pZx6IB5eEfC_E-Cc_pi2TQ" name="onboardingStatusBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.OnboardingStatus">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pZx6IR5eEfC_E-Cc_pi2TQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_sOTQMB5eEfC_E-Cc_pi2TQ" name="tradingAccountBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.TradingAccount">
        <defaultValue xmi:type="expression:Expression" xmi:id="_sOTQMR5eEfC_E-Cc_pi2TQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_vEnWAB5eEfC_E-Cc_pi2TQ" name="chessHinRequestBusinessObject" dataType="_P5zuFBqPEfC8TeDcwO75Gw" className="com.company.model.CHESSHINRequest">
        <defaultValue xmi:type="expression:Expression" xmi:id="_vEnWAR5eEfC_E-Cc_pi2TQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_7UGccB_kEfC_E-Cc_pi2TQ" name="instrumentTransferRequest" dataType="_P5zuDBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_7UGccR_kEfC_E-Cc_pi2TQ" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pWflkCAfEfC_E-Cc_pi2TQ" name="wealthOver1Million" dataType="_P5zuDBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pWflkSAfEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Czkc4CAgEfC_E-Cc_pi2TQ" name="currentWealth" dataType="_P5zuEBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Czkc4SAgEfC_E-Cc_pi2TQ" content="" returnType="java.lang.Double"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_F1ybQCAhEfC_E-Cc_pi2TQ" name="clientApproved" dataType="_P5zuDBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_F1ybQSAhEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_d-OgQCA0EfC_E-Cc_pi2TQ" name="dailyLimit" dataType="_P5zuEBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d-OgQSA0EfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Double"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_FVuEACA1EfC_E-Cc_pi2TQ" name="availableFunds" dataType="_P5zuEBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_FVuEASA1EfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Double"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_8LNxYCA2EfC_E-Cc_pi2TQ" name="hasHIN" dataType="_P5zuDBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_8LNxYSA2EfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_WNCCkCA5EfC_E-Cc_pi2TQ" name="signupSource" dataType="_P5zuERqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_WNCCkSA5EfC_E-Cc_pi2TQ" name="" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_L3YLcCA7EfC_E-Cc_pi2TQ" name="transferRequested" dataType="_P5zuDBqPEfC8TeDcwO75Gw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_L3YLcSA7EfC_E-Cc_pi2TQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_P5zt9BqPEfC8TeDcwO75Gw">
        <targetForm xmi:type="expression:Expression" xmi:id="_iF60ySA8EfC_E-Cc_pi2TQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_P5zt9hqPEfC8TeDcwO75Gw">
        <targetForm xmi:type="expression:Expression" xmi:id="_P5zt9xqPEfC8TeDcwO75Gw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ba2UgBqQEfC8TeDcwO75Gw" target="_71zXkBqPEfC8TeDcwO75Gw" source="_P5zt4xqPEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ba2UgRqQEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ba2UghqQEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__-EikBqREfC8TeDcwO75Gw" target="_x_yp0BqREfC8TeDcwO75Gw" source="_kwYpQBqREfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__-EikRqREfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="__-EikhqREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JkxhoBqTEfC8TeDcwO75Gw" target="_FneloBqTEfC8TeDcwO75Gw" source="_x_yp0BqREfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JkyvwBqTEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_JkyvwRqTEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_X1hYgBqVEfC8TeDcwO75Gw" target="_vX67IB_gEfC_E-Cc_pi2TQ" source="_Q123sBqVEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_X1hYgRqVEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_X1hYghqVEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VTxYABqWEfC8TeDcwO75Gw" target="_S0ocEBqWEfC8TeDcwO75Gw" source="_TUkLQBqUEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VTxYARqWEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_VTxYAhqWEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1hhR4BqWEfC8TeDcwO75Gw" name="Yes" target="_tViu8BqWEfC8TeDcwO75Gw" source="_S0ocEBqWEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1hhR4RqWEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1hhR4hqWEfC8TeDcwO75Gw" name="currentWealth()" content="currentWealth > 1000000" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_fmhD0CAgEfC_E-Cc_pi2TQ" name="currentWealth" dataType="_P5zuEBqPEfC8TeDcwO75Gw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Rli5IBqeEfC8TeDcwO75Gw" target="_OVePgBqeEfC8TeDcwO75Gw" source="_snSsYBqXEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Rli5IRqeEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Rli5IhqeEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fm9wABqfEfC8TeDcwO75Gw" target="_btNQMBqfEfC8TeDcwO75Gw" source="_ROq0wBqfEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fm-XEBqfEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_fm-XERqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gIAAgBqfEfC8TeDcwO75Gw" name="No" target="_duOswBqfEfC8TeDcwO75Gw" source="_btNQMBqfEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gIAnkBqfEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gIAnkRqfEfC8TeDcwO75Gw" name="newScript()" content="clientApproved == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_FRZfUCAiEfC_E-Cc_pi2TQ" name="clientApproved" dataType="_P5zuDBqPEfC8TeDcwO75Gw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pr2VUBqfEfC8TeDcwO75Gw" name="Yes" target="_mSP8QBqfEfC8TeDcwO75Gw" source="_btNQMBqfEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pr2VURqfEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_pr28YBqfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gtgr4BqgEfC8TeDcwO75Gw" target="_d_MEcBqgEfC8TeDcwO75Gw" source="_mSP8QBqfEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gtgr4RqgEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_gtgr4hqgEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mOqAQBqgEfC8TeDcwO75Gw" name="No" target="_kOCMUBqgEfC8TeDcwO75Gw" source="_d_MEcBqgEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mOqAQRqgEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_mOqAQhqgEfC8TeDcwO75Gw" name="limit &lt; available funds" content="dailyLimit &lt; availableFunds" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_hk-vECA1EfC_E-Cc_pi2TQ" name="dailyLimit" dataType="_P5zuEBqPEfC8TeDcwO75Gw"/>
          <referencedElements xmi:type="process:Data" xmi:id="_hk-vESA1EfC_E-Cc_pi2TQ" name="availableFunds" dataType="_P5zuEBqPEfC8TeDcwO75Gw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XLeYIBqkEfC8TeDcwO75Gw" target="_V_npABqkEfC8TeDcwO75Gw" source="_71zXkBqPEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XLeYIRqkEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_XLeYIhqkEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iyjI8BqkEfC8TeDcwO75Gw" name="Via Sales Team" target="_PlaGABqhEfC8TeDcwO75Gw" source="_V_npABqkEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iyjI8RqkEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_iyjI8hqkEfC8TeDcwO75Gw" name="SalesSignupSource()" content="signupSource == &quot;Sales&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_cbP4UCA5EfC_E-Cc_pi2TQ" name="signupSource" dataType="_P5zuERqPEfC8TeDcwO75Gw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l6yk4BqnEfC8TeDcwO75Gw" name="HIN Provided" target="_kZNdYBqnEfC8TeDcwO75Gw" source="_WYMZsBqnEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l6yk4RqnEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_l6yk4hqnEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vBGhYBzREfC8TeDcwO75Gw" target="_aM8-IB2vEfC8TeDcwO75Gw" source="_UhPXYBzREfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vBHvgBzREfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_vBHvgRzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5iSBIBzREfC8TeDcwO75Gw" target="_2nLh8BzREfC8TeDcwO75Gw" source="_aM8-IB2vEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5iSBIRzREfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_5iSBIhzREfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oacc0BzZEfC8TeDcwO75Gw" name="Yes" target="_WYMZsBqnEfC8TeDcwO75Gw" source="_d_MEcBqgEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oacc0RzZEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_oacc0hzZEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_f6kewBzfEfC8TeDcwO75Gw" target="_Zhp50B_dEfC_E-Cc_pi2TQ" source="_2nLh8BzREfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_f6lF0BzfEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_f6lF0RzfEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4_m-oBzhEfC8TeDcwO75Gw" name="Yes, process exceeds 30 days" target="_ejLVYBzcEfC8TeDcwO75Gw" source="_fC1JABzgEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4_m-oRzhEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_4_m-ohzhEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DCVV4BzkEfC8TeDcwO75Gw" name="no" target="_Bq5o4BzkEfC8TeDcwO75Gw" source="_fC1JABzgEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DCVV4RzkEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_DCVV4hzkEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8tkkgBzpEfC8TeDcwO75Gw" name="Review declined " target="_6-6qUBzpEfC8TeDcwO75Gw" source="_kOCMUBqgEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8tkkgRzpEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_8tkkghzpEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Kg9mcBzrEfC8TeDcwO75Gw" target="_F4BscBzrEfC8TeDcwO75Gw" source="_WYMZsBqnEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Kg9mcRzrEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Kg9mchzrEfC8TeDcwO75Gw" name="Client HIN check()" content="hasHIN == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_AydpUCA3EfC_E-Cc_pi2TQ" name="hasHIN" dataType="_P5zuDBqPEfC8TeDcwO75Gw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MytmoBzrEfC8TeDcwO75Gw" name="Yes" target="_kZNdYBqnEfC8TeDcwO75Gw" source="_F4BscBzrEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MytmoRzrEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_MytmohzrEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_P3iCgBzrEfC8TeDcwO75Gw" name="No" target="_OXnu8BzrEfC8TeDcwO75Gw" source="_F4BscBzrEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_P3iCgRzrEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_P3iCghzrEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S0sXMBzrEfC8TeDcwO75Gw" target="_s-U5EBqnEfC8TeDcwO75Gw" source="_kZNdYBqnEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S0sXMRzrEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_S0sXMhzrEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jvwKIBzrEfC8TeDcwO75Gw" target="_ROq0wBqfEfC8TeDcwO75Gw" source="_OVePgBqeEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jvwxMBzrEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_jvwxMRzrEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ndw9cB2pEfC8TeDcwO75Gw" target="_fC1JABzgEfC8TeDcwO75Gw" source="_Zhp50B_dEfC_E-Cc_pi2TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ndw9cR2pEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_NdxkgB2pEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hlPpEB2pEfC8TeDcwO75Gw" target="_TUkLQBqUEfC8TeDcwO75Gw" source="_vX67IB_gEfC_E-Cc_pi2TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hlPpER2pEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_hlPpEh2pEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ww-PkB2tEfC8TeDcwO75Gw" name="No" target="_u5phkB2tEfC8TeDcwO75Gw" source="_S0ocEBqWEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ww-PkR2tEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ww-Pkh2tEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zUJ-AB2tEfC8TeDcwO75Gw" target="_u5phkB2tEfC8TeDcwO75Gw" source="_tViu8BqWEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zUJ-AR2tEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_zUJ-Ah2tEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0goYMB2tEfC8TeDcwO75Gw" target="_snSsYBqXEfC8TeDcwO75Gw" source="_u5phkB2tEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0goYMR2tEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_0goYMh2tEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PKhn8B2uEfC8TeDcwO75Gw" target="_NFLFAB2uEfC8TeDcwO75Gw" source="_PlaGABqhEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PKhn8R2uEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_PKhn8h2uEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SDPhgB2uEfC8TeDcwO75Gw" name="via Website" target="_NFLFAB2uEfC8TeDcwO75Gw" source="_V_npABqkEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SDPhgR2uEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_SDPhgh2uEfC8TeDcwO75Gw" name="WebsiteSignupSource()" content="signupSource == &quot;Website&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_jkz8ACA5EfC_E-Cc_pi2TQ" name="signupSource" dataType="_P5zuERqPEfC8TeDcwO75Gw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SmW1oB2uEfC8TeDcwO75Gw" target="_kwYpQBqREfC8TeDcwO75Gw" source="_NFLFAB2uEfC8TeDcwO75Gw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SmXcsB2uEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_SmXcsR2uEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qfMoIB2wEfC8TeDcwO75Gw" target="_Bq5o4BzkEfC8TeDcwO75Gw" source="_ejLVYBzcEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qfMoIR2wEfC8TeDcwO75Gw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qfMoIh2wEfC8TeDcwO75Gw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eYGcwB5bEfC_E-Cc_pi2TQ" target="_Q123sBqVEfC8TeDcwO75Gw" source="_FneloBqTEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eYHD0B5bEfC_E-Cc_pi2TQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_eYHD0R5bEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uHu-YB5bEfC_E-Cc_pi2TQ" target="_m_oTQB5bEfC_E-Cc_pi2TQ" source="_R0hSUB5ZEfC_E-Cc_pi2TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uHu-YR5bEfC_E-Cc_pi2TQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_uHu-Yh5bEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vZkZsB5bEfC_E-Cc_pi2TQ" name="Transfer requested" target="_R0hSUB5ZEfC_E-Cc_pi2TQ" source="_TsDw0B5bEfC_E-Cc_pi2TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vZkZsR5bEfC_E-Cc_pi2TQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vZkZsh5bEfC_E-Cc_pi2TQ" name="TransferRequest()" content="transferRequested == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_PmFR0CA7EfC_E-Cc_pi2TQ" name="transferRequested" dataType="_P5zuDBqPEfC8TeDcwO75Gw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xBeysB5bEfC_E-Cc_pi2TQ" name="Transfer not requested" target="_m_oTQB5bEfC_E-Cc_pi2TQ" source="_TsDw0B5bEfC_E-Cc_pi2TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xBeysR5bEfC_E-Cc_pi2TQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_xBeysh5bEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3g67UB5bEfC_E-Cc_pi2TQ" target="_TsDw0B5bEfC_E-Cc_pi2TQ" source="_s-U5EBqnEfC8TeDcwO75Gw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3g67UR5bEfC_E-Cc_pi2TQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3g67Uh5bEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7tiswB5bEfC_E-Cc_pi2TQ" target="_UhPXYBzREfC8TeDcwO75Gw" source="_m_oTQB5bEfC_E-Cc_pi2TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7tiswR5bEfC_E-Cc_pi2TQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7tiswh5bEfC_E-Cc_pi2TQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_P5zt-xqPEfC8TeDcwO75Gw" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor"/>
      <actors xmi:type="process:Actor" xmi:id="_OELTkB5hEfC_E-Cc_pi2TQ" name="KYC Risk Team" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_P5zt_BqPEfC8TeDcwO75Gw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_P5zt_RqPEfC8TeDcwO75Gw">
        <name xmi:type="expression:Expression" xmi:id="_P5zt_hqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_P5zt_xqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_P5zuABqPEfC8TeDcwO75Gw">
        <name xmi:type="expression:Expression" xmi:id="_P5zuARqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_P5zuAhqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_P5zuAxqPEfC8TeDcwO75Gw">
        <name xmi:type="expression:Expression" xmi:id="_P5zuBBqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_P5zuBRqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_P5zuBhqPEfC8TeDcwO75Gw">
        <name xmi:type="expression:Expression" xmi:id="_P5zuBxqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_P5zuCBqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_P5zuCRqPEfC8TeDcwO75Gw">
        <name xmi:type="expression:Expression" xmi:id="_P5zuChqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_P5zuCxqPEfC8TeDcwO75Gw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_P5zuDBqPEfC8TeDcwO75Gw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_P5zuDRqPEfC8TeDcwO75Gw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_P5zuDhqPEfC8TeDcwO75Gw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_P5zuDxqPEfC8TeDcwO75Gw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_P5zuEBqPEfC8TeDcwO75Gw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_P5zuERqPEfC8TeDcwO75Gw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_P5zuEhqPEfC8TeDcwO75Gw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_P5zuExqPEfC8TeDcwO75Gw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_P5zuFBqPEfC8TeDcwO75Gw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_P5zuFRqPEfC8TeDcwO75Gw" type="Process" element="_P5zt4BqPEfC8TeDcwO75Gw" name="MyDiagram2" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_P5zuFhqPEfC8TeDcwO75Gw" type="2007" element="_P5zt4RqPEfC8TeDcwO75Gw">
      <children xmi:type="notation:DecorationNode" xmi:id="_P5zuFxqPEfC8TeDcwO75Gw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_P5zuGBqPEfC8TeDcwO75Gw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_P5zuGRqPEfC8TeDcwO75Gw" type="3007" element="_P5zt4hqPEfC8TeDcwO75Gw">
          <children xmi:type="notation:DecorationNode" xmi:id="_P5zuGhqPEfC8TeDcwO75Gw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_P5zuGxqPEfC8TeDcwO75Gw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_P50U8RqPEfC8TeDcwO75Gw" type="3002" element="_P5zt4xqPEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_P50U8hqPEfC8TeDcwO75Gw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_P50U8xqPEfC8TeDcwO75Gw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P50U9BqPEfC8TeDcwO75Gw" x="105" y="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_719voBqPEfC8TeDcwO75Gw" type="3005" element="_71zXkBqPEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_719vohqPEfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_719voRqPEfC8TeDcwO75Gw" x="301" y="52" width="167" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kwZQVBqREfC8TeDcwO75Gw" type="3005" element="_kwYpQBqREfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kwZ3YBqREfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kwZQVRqREfC8TeDcwO75Gw" x="818" y="55" width="156" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x_zQ5hqREfC8TeDcwO75Gw" type="3005" element="_x_yp0BqREfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x_z38BqREfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x_zQ5xqREfC8TeDcwO75Gw" x="1057" y="52" width="166" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FnelqRqTEfC8TeDcwO75Gw" type="3006" element="_FneloBqTEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FnelqxqTEfC8TeDcwO75Gw" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FnelqhqTEfC8TeDcwO75Gw" x="1281" y="49" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_V_o3IBqkEfC8TeDcwO75Gw" type="3008" element="_V_npABqkEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_V_o3IhqkEfC8TeDcwO75Gw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_V_o3IxqkEfC8TeDcwO75Gw" x="9" y="-77"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_V_o3IRqkEfC8TeDcwO75Gw" x="555" y="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NFLsEB2uEfC8TeDcwO75Gw" type="3008" element="_NFLFAB2uEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NFLsEh2uEfC8TeDcwO75Gw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NFLsEx2uEfC8TeDcwO75Gw" x="77" y="10"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NFLsER2uEfC8TeDcwO75Gw" x="706" y="146"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_R0xxAB5ZEfC_E-Cc_pi2TQ" type="3006" element="_R0hSUB5ZEfC_E-Cc_pi2TQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_R0yYEB5ZEfC_E-Cc_pi2TQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R0xxAR5ZEfC_E-Cc_pi2TQ" x="1311" y="279" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TsEX4B5bEfC_E-Cc_pi2TQ" type="3008" element="_TsDw0B5bEfC_E-Cc_pi2TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TsEX4h5bEfC_E-Cc_pi2TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TsEX4x5bEfC_E-Cc_pi2TQ" x="-91" y="-10"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TsEX4R5bEfC_E-Cc_pi2TQ" x="1143" y="290"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_m_phYB5bEfC_E-Cc_pi2TQ" type="3008" element="_m_oTQB5bEfC_E-Cc_pi2TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_m_phYh5bEfC_E-Cc_pi2TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_m_phYx5bEfC_E-Cc_pi2TQ" x="144" y="-23"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m_phYR5bEfC_E-Cc_pi2TQ" x="1560" y="283"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Zhqg4B_dEfC_E-Cc_pi2TQ" type="3026" element="_Zhp50B_dEfC_E-Cc_pi2TQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Zhqg4h_dEfC_E-Cc_pi2TQ" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zhqg4R_dEfC_E-Cc_pi2TQ" x="1993" y="55" width="170" height="84"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_P50U9RqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_P50U9hqPEfC8TeDcwO75Gw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_P50U9xqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_P50U-BqPEfC8TeDcwO75Gw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P50U-RqPEfC8TeDcwO75Gw" x="58" y="10" width="2487" height="430"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_ViwTYBqPEfC8TeDcwO75Gw" type="3007" element="_ViueMBqPEfC8TeDcwO75Gw">
          <children xmi:type="notation:DecorationNode" xmi:id="_VixhgBqPEfC8TeDcwO75Gw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VixhgRqPEfC8TeDcwO75Gw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TUkyWBqUEfC8TeDcwO75Gw" type="3006" element="_TUkLQBqUEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TUlZYBqUEfC8TeDcwO75Gw" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TUkyWRqUEfC8TeDcwO75Gw" x="556" y="77" width="179" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Q14F0BqVEfC8TeDcwO75Gw" type="3025" element="_Q123sBqVEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q14F0hqVEfC8TeDcwO75Gw" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q14F0RqVEfC8TeDcwO75Gw" x="331" y="80" width="176" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_S0q4UBqWEfC8TeDcwO75Gw" type="3008" element="_S0ocEBqWEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_S0q4UhqWEfC8TeDcwO75Gw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_S0q4UxqWEfC8TeDcwO75Gw" x="5" y="-81"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_S0q4URqWEfC8TeDcwO75Gw" x="857" y="108"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tVjWABqWEfC8TeDcwO75Gw" type="3005" element="_tViu8BqWEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tVj9EBqWEfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tVjWARqWEfC8TeDcwO75Gw" x="998" y="86" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UhQlgBzREfC8TeDcwO75Gw" type="3027" element="_UhPXYBzREfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UhRMkBzREfC8TeDcwO75Gw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UhQlgRzREfC8TeDcwO75Gw" x="1353" y="83" width="187" height="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2nMJABzREfC8TeDcwO75Gw" type="3005" element="_2nLh8BzREfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2nMJAhzREfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2nMJARzREfC8TeDcwO75Gw" x="1843" y="78" width="182" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fC1wExzgEfC8TeDcwO75Gw" type="3017" element="_fC1JABzgEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fC2-MBzgEfC8TeDcwO75Gw" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fC2-MRzgEfC8TeDcwO75Gw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fC1wFBzgEfC8TeDcwO75Gw" x="2093" y="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Bq63ABzkEfC8TeDcwO75Gw" type="3003" element="_Bq5o4BzkEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Bq63AhzkEfC8TeDcwO75Gw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Bq63AxzkEfC8TeDcwO75Gw" x="-60" y="20"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Bq63ARzkEfC8TeDcwO75Gw" x="2345" y="104"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_u5qvsB2tEfC8TeDcwO75Gw" type="3008" element="_u5phkB2tEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_u5qvsh2tEfC8TeDcwO75Gw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_u5qvsx2tEfC8TeDcwO75Gw" x="39" y="12"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_u5qvsR2tEfC8TeDcwO75Gw" x="916" y="300"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aM9lOR2vEfC8TeDcwO75Gw" type="3005" element="_aM8-IB2vEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_aM9lOx2vEfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aM9lOh2vEfC8TeDcwO75Gw" x="1591" y="85" width="181" height="90"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ViwTYRqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ViwTYhqPEfC8TeDcwO75Gw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ViwTYxqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VixhghqPEfC8TeDcwO75Gw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ViwTZBqPEfC8TeDcwO75Gw" x="58" y="400" width="2487" height="518"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_V0WZsBqPEfC8TeDcwO75Gw" type="3007" element="_V0VyoBqPEfC8TeDcwO75Gw">
          <children xmi:type="notation:DecorationNode" xmi:id="_V0WZtRqPEfC8TeDcwO75Gw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_V0WZthqPEfC8TeDcwO75Gw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PlatFhqhEfC8TeDcwO75Gw" type="3027" element="_PlaGABqhEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PlatGBqhEfC8TeDcwO75Gw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PlatFxqhEfC8TeDcwO75Gw" x="160" y="78" width="195" height="97"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_V0WZsRqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_V0WZshqPEfC8TeDcwO75Gw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_V0WZsxqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_V0WZtxqPEfC8TeDcwO75Gw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_V0WZtBqPEfC8TeDcwO75Gw" x="58" y="650" width="1587" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_WKzx4BqPEfC8TeDcwO75Gw" type="3007" element="_WKzK0BqPEfC8TeDcwO75Gw">
          <children xmi:type="notation:DecorationNode" xmi:id="_WKzx5RqPEfC8TeDcwO75Gw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_WKzx5hqPEfC8TeDcwO75Gw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_snUhkBqXEfC8TeDcwO75Gw" type="3027" element="_snSsYBqXEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_snUhkhqXEfC8TeDcwO75Gw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_snUhkRqXEfC8TeDcwO75Gw" x="891" y="82" width="172" height="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OVfdoBqeEfC8TeDcwO75Gw" type="3006" element="_OVePgBqeEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OVfdohqeEfC8TeDcwO75Gw" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OVfdoRqeEfC8TeDcwO75Gw" x="1171" y="82" width="182" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vX7iOB_gEfC_E-Cc_pi2TQ" type="3026" element="_vX67IB_gEfC_E-Cc_pi2TQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vX7iOh_gEfC_E-Cc_pi2TQ" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vX7iOR_gEfC_E-Cc_pi2TQ" x="331" y="54" width="180" height="89"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_WKzx4RqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_WKzx4hqPEfC8TeDcwO75Gw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_WKzx4xqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_WKzx5xqPEfC8TeDcwO75Gw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WKzx5BqPEfC8TeDcwO75Gw" x="58" y="600" width="1287" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_WfExsBqPEfC8TeDcwO75Gw" type="3007" element="_WfEKoBqPEfC8TeDcwO75Gw">
          <children xmi:type="notation:DecorationNode" xmi:id="_WfExtRqPEfC8TeDcwO75Gw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_WfExthqPEfC8TeDcwO75Gw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ROsC4BqfEfC8TeDcwO75Gw" type="3005" element="_ROq0wBqfEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ROsp8BqfEfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ROsC4RqfEfC8TeDcwO75Gw" x="101" y="157" width="182" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_btOeUBqfEfC8TeDcwO75Gw" type="3008" element="_btNQMBqfEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_btOeUhqfEfC8TeDcwO75Gw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_btOeUxqfEfC8TeDcwO75Gw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_btOeURqfEfC8TeDcwO75Gw" x="355" y="168"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_duP64BqfEfC8TeDcwO75Gw" type="3003" element="_duOswBqfEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_duQh8BqfEfC8TeDcwO75Gw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_duQh8RqfEfC8TeDcwO75Gw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_duP64RqfEfC8TeDcwO75Gw" x="483" y="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mSRKaRqfEfC8TeDcwO75Gw" type="3005" element="_mSP8QBqfEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mSRxcBqfEfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mSRKahqfEfC8TeDcwO75Gw" x="571" y="153" width="195" height="97"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_d_MrgRqgEfC8TeDcwO75Gw" type="3008" element="_d_MEcBqgEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d_MrgxqgEfC8TeDcwO75Gw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_d_MrhBqgEfC8TeDcwO75Gw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_d_MrghqgEfC8TeDcwO75Gw" x="917" y="156"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kODacBqgEfC8TeDcwO75Gw" type="3005" element="_kOCMUBqgEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kODachqgEfC8TeDcwO75Gw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kODacRqgEfC8TeDcwO75Gw" x="1113" y="29" width="179" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6-7RYBzpEfC8TeDcwO75Gw" type="3003" element="_6-6qUBzpEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6-7RYhzpEfC8TeDcwO75Gw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6-7RYxzpEfC8TeDcwO75Gw" x="-79" y="26"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6-7RYRzpEfC8TeDcwO75Gw" x="1364" y="167"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_WfExsRqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_WfExshqPEfC8TeDcwO75Gw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_WfExsxqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_WfExtxqPEfC8TeDcwO75Gw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WfExtBqPEfC8TeDcwO75Gw" x="58" y="1200" width="1587" height="480"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_fpyNwRqPEfC8TeDcwO75Gw" type="3007" element="_fpyNwBqPEfC8TeDcwO75Gw">
          <children xmi:type="notation:DecorationNode" xmi:id="_fpy00BqPEfC8TeDcwO75Gw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_fpy00RqPEfC8TeDcwO75Gw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ejL8cBzcEfC8TeDcwO75Gw" type="3026" element="_ejLVYBzcEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ejL8chzcEfC8TeDcwO75Gw" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ejL8cRzcEfC8TeDcwO75Gw" x="1871" y="70" width="174" height="87"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_fpyNwhqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_fpyNwxqPEfC8TeDcwO75Gw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_fpyNxBqPEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_fpy00hqPEfC8TeDcwO75Gw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fpyNxRqPEfC8TeDcwO75Gw" x="58" y="1100" width="1287" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_M_gMABqnEfC8TeDcwO75Gw" type="3007" element="_M_e94BqnEfC8TeDcwO75Gw">
          <children xmi:type="notation:DecorationNode" xmi:id="_M_gMBRqnEfC8TeDcwO75Gw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_M_gMBhqnEfC8TeDcwO75Gw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_WYNn0xqnEfC8TeDcwO75Gw" type="3008" element="_WYMZsBqnEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_WYOO4BqnEfC8TeDcwO75Gw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WYOO4RqnEfC8TeDcwO75Gw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WYNn1BqnEfC8TeDcwO75Gw" x="245" y="192"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kZOrgBqnEfC8TeDcwO75Gw" type="3027" element="_kZNdYBqnEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kZOrghqnEfC8TeDcwO75Gw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kZOrgRqnEfC8TeDcwO75Gw" x="553" y="196" width="179" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s-WHMBqnEfC8TeDcwO75Gw" type="3027" element="_s-U5EBqnEfC8TeDcwO75Gw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s-WuQBqnEfC8TeDcwO75Gw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s-WHMRqnEfC8TeDcwO75Gw" x="842" y="192" width="193" height="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F4DhoBzrEfC8TeDcwO75Gw" type="3017" element="_F4BscBzrEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F4DhohzrEfC8TeDcwO75Gw" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F4DhoxzrEfC8TeDcwO75Gw" x="-68" y="-56"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F4DhoRzrEfC8TeDcwO75Gw" x="438" y="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OXoWAxzrEfC8TeDcwO75Gw" type="3003" element="_OXnu8BzrEfC8TeDcwO75Gw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_OXoWBRzrEfC8TeDcwO75Gw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_OXoWBhzrEfC8TeDcwO75Gw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OXoWBBzrEfC8TeDcwO75Gw" x="693" y="62"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_M_gMARqnEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_M_gMAhqnEfC8TeDcwO75Gw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_M_gMAxqnEfC8TeDcwO75Gw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_M_gMBxqnEfC8TeDcwO75Gw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M_gMBBqnEfC8TeDcwO75Gw" x="58" y="1680" width="1737" height="390"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_P50U-hqPEfC8TeDcwO75Gw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_P50U-xqPEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_P50U_BqPEfC8TeDcwO75Gw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_P50U_RqPEfC8TeDcwO75Gw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P50U_hqPEfC8TeDcwO75Gw" width="2520" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_P50U_xqPEfC8TeDcwO75Gw"/>
    <edges xmi:type="notation:Connector" xmi:id="_Ba27kBqQEfC8TeDcwO75Gw" type="4001" element="_Ba2UgBqQEfC8TeDcwO75Gw" source="_P50U8RqPEfC8TeDcwO75Gw" target="_719voBqPEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ba3ioBqQEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ba3ioRqQEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ba27kRqQEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ba27khqQEfC8TeDcwO75Gw" points="[-1, -16, -250, 0]$[166, -43, -83, -27]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ba4wwBqQEfC8TeDcwO75Gw" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__-FJoBqREfC8TeDcwO75Gw" type="4001" element="__-EikBqREfC8TeDcwO75Gw" source="_kwZQVBqREfC8TeDcwO75Gw" target="_x_zQ5hqREfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__-FJoxqREfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__-FJpBqREfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__-FJoRqREfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__-FJohqREfC8TeDcwO75Gw" points="[0, 4, -176, 0]$[105, 4, -71, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__-G-0BqREfC8TeDcwO75Gw" id="(1.0,0.4358974358974359)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JkyvwhqTEfC8TeDcwO75Gw" type="4001" element="_JkxhoBqTEfC8TeDcwO75Gw" source="_x_zQ5hqREfC8TeDcwO75Gw" target="_FnelqRqTEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JkyvxRqTEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JkyvxhqTEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JkyvwxqTEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JkyvxBqTEfC8TeDcwO75Gw" points="[0, 9, -107, 1]$[44, 9, -63, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Jkz94BqTEfC8TeDcwO75Gw" id="(1.0,0.37349397590361444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_X1h_kBqVEfC8TeDcwO75Gw" type="4001" element="_X1hYgBqVEfC8TeDcwO75Gw" source="_Q14F0BqVEfC8TeDcwO75Gw" target="_vX7iOB_gEfC_E-Cc_pi2TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_X1h_kxqVEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_X1h_lBqVEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_X1h_kRqVEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X1h_khqVEfC8TeDcwO75Gw" points="[-33, 56, -35, -513]$[-33, 290, -35, -279]$[-5, 290, -7, -279]$[-5, 524, -7, -45]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_X1imoBqVEfC8TeDcwO75Gw" id="(1.0,0.36363636363636365)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VTx_EBqWEfC8TeDcwO75Gw" type="4001" element="_VTxYABqWEfC8TeDcwO75Gw" source="_TUkyWBqUEfC8TeDcwO75Gw" target="_S0q4UBqWEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VTx_ExqWEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VTx_FBqWEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VTx_ERqWEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VTx_EhqWEfC8TeDcwO75Gw" points="[0, 0, -68, -22]$[75, 12, 7, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VTymIBqWEfC8TeDcwO75Gw" id="(1.0,0.3595505617977528)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1hmKYBqWEfC8TeDcwO75Gw" type="4001" element="_1hhR4BqWEfC8TeDcwO75Gw" source="_S0q4UBqWEfC8TeDcwO75Gw" target="_tVjWABqWEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1hmKYxqWEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1hmKZBqWEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1hmKYRqWEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1hmKYhqWEfC8TeDcwO75Gw" points="[-3, -8, -148, -16]$[121, -8, -24, -16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1hnYgBqWEfC8TeDcwO75Gw" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1hnYgRqWEfC8TeDcwO75Gw" id="(0.13793103448275862,0.5747126436781609)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RljgMBqeEfC8TeDcwO75Gw" type="4001" element="_Rli5IBqeEfC8TeDcwO75Gw" source="_snUhkBqXEfC8TeDcwO75Gw" target="_OVfdoBqeEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RljgMxqeEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RljgNBqeEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RljgMRqeEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RljgMhqeEfC8TeDcwO75Gw" points="[0, 1, -82, 1]$[82, -25, 0, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RlkHQBqeEfC8TeDcwO75Gw" id="(1.0,0.36046511627906974)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RlkHQRqeEfC8TeDcwO75Gw" id="(0.17582417582417584,0.37362637362637363)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fm-XEhqfEfC8TeDcwO75Gw" type="4001" element="_fm9wABqfEfC8TeDcwO75Gw" source="_ROsC4BqfEfC8TeDcwO75Gw" target="_btOeUBqfEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fm-XFRqfEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fm-XFhqfEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fm-XExqfEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fm-XFBqfEfC8TeDcwO75Gw" points="[0, 3, -68, 0]$[68, -2, 0, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fm_lMBqfEfC8TeDcwO75Gw" id="(1.0,0.3626373626373626)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fm_lMRqfEfC8TeDcwO75Gw" id="(0.4418604651162791,0.18604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gIAnkhqfEfC8TeDcwO75Gw" type="4001" element="_gIAAgBqfEfC8TeDcwO75Gw" source="_btOeUBqfEfC8TeDcwO75Gw" target="_duP64BqfEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gIAnlRqfEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gIAnlhqfEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gIAnkxqfEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gIAnlBqfEfC8TeDcwO75Gw" points="[-22, -30, -111, 66]$[-22, -94, -111, 2]$[86, -94, -3, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gIB1sBqfEfC8TeDcwO75Gw" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gIB1sRqfEfC8TeDcwO75Gw" id="(0.13333333333333333,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pr704BqfEfC8TeDcwO75Gw" type="4001" element="_pr2VUBqfEfC8TeDcwO75Gw" source="_btOeUBqfEfC8TeDcwO75Gw" target="_mSRKaRqfEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pr704xqfEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pr705BqfEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pr704RqfEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pr704hqfEfC8TeDcwO75Gw" points="[-2, -3, -173, 0]$[138, -2, -33, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pr9DABqfEfC8TeDcwO75Gw" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pr9DARqfEfC8TeDcwO75Gw" id="(0.23076923076923078,0.5257731958762887)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gthS8BqgEfC8TeDcwO75Gw" type="4001" element="_gtgr4BqgEfC8TeDcwO75Gw" source="_mSRKaRqfEfC8TeDcwO75Gw" target="_d_MrgRqgEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gthS8xqgEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gthS9BqgEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gthS8RqgEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gthS8hqgEfC8TeDcwO75Gw" points="[0, 0, -80, -13]$[76, 0, -4, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gtihEBqgEfC8TeDcwO75Gw" id="(1.0,0.31958762886597936)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mOqAQxqgEfC8TeDcwO75Gw" type="4001" element="_mOqAQBqgEfC8TeDcwO75Gw" source="_d_MrgRqgEfC8TeDcwO75Gw" target="_kODacBqgEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mOqnUBqgEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mOqnURqgEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mOqARBqgEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mOqARRqgEfC8TeDcwO75Gw" points="[-25, -27, -96, 86]$[-25, -97, -96, 16]$[31, -97, -40, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mOrOYBqgEfC8TeDcwO75Gw" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mOrOYRqgEfC8TeDcwO75Gw" id="(0.31746031746031744,0.20634920634920634)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XLe_MBqkEfC8TeDcwO75Gw" type="4001" element="_XLeYIBqkEfC8TeDcwO75Gw" source="_719voBqPEfC8TeDcwO75Gw" target="_V_o3IBqkEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XLe_MxqkEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XLe_NBqkEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XLe_MRqkEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XLe_MhqkEfC8TeDcwO75Gw" points="[0, -6, -89, 9]$[70, -6, -19, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XLgNUBqkEfC8TeDcwO75Gw" id="(1.0,0.40963855421686746)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XLgNURqkEfC8TeDcwO75Gw" id="(0.4883720930232558,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iypPkBqkEfC8TeDcwO75Gw" type="4001" element="_iyjI8BqkEfC8TeDcwO75Gw" source="_V_o3IBqkEfC8TeDcwO75Gw" target="_PlatFhqhEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iypPkxqkEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iypPlBqkEfC8TeDcwO75Gw" x="-160" y="-192"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iypPkRqkEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iypPkhqkEfC8TeDcwO75Gw" points="[-23, 12, 318, -961]$[-23, 115, 318, -858]$[-430, 115, -89, -858]$[-430, 925, -89, -48]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iyqdsBqkEfC8TeDcwO75Gw" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l63dYBqnEfC8TeDcwO75Gw" type="4001" element="_l6yk4BqnEfC8TeDcwO75Gw" source="_WYNn0xqnEfC8TeDcwO75Gw" target="_kZOrgBqnEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l63dYxqnEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l63dZBqnEfC8TeDcwO75Gw" x="32" y="-27"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l63dYRqnEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l63dYhqnEfC8TeDcwO75Gw" points="[-23, 13, -143, 22]$[-23, 18, -143, 27]$[69, 18, -51, 27]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_l63dZRqnEfC8TeDcwO75Gw" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_l64rgBqnEfC8TeDcwO75Gw" id="(0.2857142857142857,0.2222222222222222)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vBHvghzREfC8TeDcwO75Gw" type="4001" element="_vBGhYBzREfC8TeDcwO75Gw" source="_UhQlgBzREfC8TeDcwO75Gw" target="_aM9lOR2vEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vBIWkBzREfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vBIWkRzREfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vBHvgxzREfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vBHvhBzREfC8TeDcwO75Gw" points="[0, 6, -141, -10]$[51, 6, -90, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vBI9oBzREfC8TeDcwO75Gw" id="(1.0,0.32978723404255317)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5iSBIxzREfC8TeDcwO75Gw" type="4001" element="_5iSBIBzREfC8TeDcwO75Gw" source="_aM9lOR2vEfC8TeDcwO75Gw" target="_2nMJABzREfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5iSBJhzREfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5iSBJxzREfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5iSBJBzREfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5iSBJRzREfC8TeDcwO75Gw" points="[0, 2, -100, -6]$[32, 2, -68, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5iTPQBzREfC8TeDcwO75Gw" id="(1.0,0.37362637362637363)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oaijcBzZEfC8TeDcwO75Gw" type="4001" element="_oacc0BzZEfC8TeDcwO75Gw" source="_d_MrgRqgEfC8TeDcwO75Gw" target="_WYNn0xqnEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oajKgBzZEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oajKgRzZEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oaijcRzZEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oaijchzZEfC8TeDcwO75Gw" points="[-22, 11, 672, -494]$[-22, 204, 672, -301]$[-883, 204, -189, -301]$[-883, 496, -189, -9]$[-706, 496, -12, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oajxkBzZEfC8TeDcwO75Gw" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_f6ls4BzfEfC8TeDcwO75Gw" type="4001" element="_f6kewBzfEfC8TeDcwO75Gw" source="_2nMJABzREfC8TeDcwO75Gw" target="_Zhqg4B_dEfC_E-Cc_pi2TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_f6ls4xzfEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_f6mT8BzfEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_f6ls4RzfEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f6ls4hzfEfC8TeDcwO75Gw" points="[-47, -34, -131, 380]$[-47, -402, -131, 12]$[-1, -402, -85, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_f6niEBzfEfC8TeDcwO75Gw" id="(1.0,0.37362637362637363)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4_nlsBzhEfC8TeDcwO75Gw" type="4001" element="_4_m-oBzhEfC8TeDcwO75Gw" source="_fC1wExzgEfC8TeDcwO75Gw" target="_ejL8cBzcEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4_nlsxzhEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4_nltBzhEfC8TeDcwO75Gw" x="193" y="120"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4_nlsRzhEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4_nlshzhEfC8TeDcwO75Gw" points="[-18, 7, 102, -1905]$[-18, 1256, 102, -656]$[-129, 1256, -9, -656]$[-129, 1884, -9, -28]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4_pa4BzhEfC8TeDcwO75Gw" id="(1.0,0.7333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4_pa4RzhEfC8TeDcwO75Gw" id="(0.7586206896551724,0.3218390804597701)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DCVV4xzkEfC8TeDcwO75Gw" type="4001" element="_DCVV4BzkEfC8TeDcwO75Gw" source="_fC1wExzgEfC8TeDcwO75Gw" target="_Bq63ABzkEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DCV88BzkEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DCV88RzkEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DCVV5BzkEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DCVV5RzkEfC8TeDcwO75Gw" points="[-1, -9, -179, 1]$[175, 0, -3, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DCWkABzkEfC8TeDcwO75Gw" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8tlLkBzpEfC8TeDcwO75Gw" type="4001" element="_8tkkgBzpEfC8TeDcwO75Gw" source="_kODacBqgEfC8TeDcwO75Gw" target="_6-7RYBzpEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8tlLkxzpEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8tlLlBzpEfC8TeDcwO75Gw" x="-31" y="13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8tlLkRzpEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8tlLkhzpEfC8TeDcwO75Gw" points="[0, 6, -108, -4]$[109, -1, 1, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8tmZsBzpEfC8TeDcwO75Gw" id="(1.0,0.3595505617977528)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KhFiQBzrEfC8TeDcwO75Gw" type="4001" element="_Kg9mcBzrEfC8TeDcwO75Gw" source="_WYNn0xqnEfC8TeDcwO75Gw" target="_F4DhoBzrEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KhFiQxzrEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KhFiRBzrEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KhFiQRzrEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KhFiQhzrEfC8TeDcwO75Gw" points="[-23, -31, -194, 125]$[-23, -141, -194, 15]$[151, -141, -20, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KhHXcBzrEfC8TeDcwO75Gw" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KhHXcRzrEfC8TeDcwO75Gw" id="(0.7,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MytmoxzrEfC8TeDcwO75Gw" type="4001" element="_MytmoBzrEfC8TeDcwO75Gw" source="_F4DhoBzrEfC8TeDcwO75Gw" target="_kZOrgBqnEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MyuNsBzrEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MyuNsRzrEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MytmpBzrEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MytmpRzrEfC8TeDcwO75Gw" points="[-15, 1, -189, -149]$[-15, 46, -189, -104]$[197, 46, 23, -104]$[197, 106, 23, -44]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Myu0wBzrEfC8TeDcwO75Gw" id="(1.0,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_P3ipkBzrEfC8TeDcwO75Gw" type="4001" element="_P3iCgBzrEfC8TeDcwO75Gw" source="_F4DhoBzrEfC8TeDcwO75Gw" target="_OXoWAxzrEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_P3ipkxzrEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_P3iplBzrEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_P3ipkRzrEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_P3ipkhzrEfC8TeDcwO75Gw" points="[-1, -9, -181, 3]$[182, -1, 2, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_P3j3sBzrEfC8TeDcwO75Gw" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S0sXMxzrEfC8TeDcwO75Gw" type="4001" element="_S0sXMBzrEfC8TeDcwO75Gw" source="_kZOrgBqnEfC8TeDcwO75Gw" target="_s-WHMBqnEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S0sXNhzrEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S0sXNxzrEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S0sXNBzrEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S0sXNRzrEfC8TeDcwO75Gw" points="[0, -2, -155, -10]$[82, -22, -73, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S0tlUBzrEfC8TeDcwO75Gw" id="(1.0,0.38202247191011235)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jvwxMhzrEfC8TeDcwO75Gw" type="4001" element="_jvwKIBzrEfC8TeDcwO75Gw" source="_OVfdoBqeEfC8TeDcwO75Gw" target="_ROsC4BqfEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jvwxNRzrEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jvwxNhzrEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jvwxMxzrEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jvwxNBzrEfC8TeDcwO75Gw" points="[-156, 60, 710, -273]$[-156, 103, 710, -230]$[-866, 103, 0, -230]$[-866, 288, 0, -45]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jvxYQBzrEfC8TeDcwO75Gw" id="(1.0,0.34065934065934067)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NdyLkB2pEfC8TeDcwO75Gw" type="4001" element="_Ndw9cB2pEfC8TeDcwO75Gw" source="_Zhqg4B_dEfC_E-Cc_pi2TQ" target="_fC1wExzgEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NdyyoB2pEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NdyyoR2pEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NdyLkR2pEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NdyLkh2pEfC8TeDcwO75Gw" points="[0, 10, 57, -419]$[42, 10, 99, -419]$[42, 233, 99, -196]$[-55, 233, 2, -196]$[-55, 414, 2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Nd1O4B2pEfC8TeDcwO75Gw" id="(1.0,0.3764705882352941)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hlPpEx2pEfC8TeDcwO75Gw" type="4001" element="_hlPpEB2pEfC8TeDcwO75Gw" source="_vX7iOB_gEfC_E-Cc_pi2TQ" target="_TUkyWBqUEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hlPpFh2pEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hlPpFx2pEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hlPpFB2pEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hlPpFR2pEfC8TeDcwO75Gw" points="[0, 15, -214, 587]$[184, 15, -30, 587]$[184, -527, -30, 45]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hlQQIB2pEfC8TeDcwO75Gw" id="(1.0,0.37362637362637363)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wxRxkB2tEfC8TeDcwO75Gw" type="4001" element="_ww-PkB2tEfC8TeDcwO75Gw" source="_S0q4UBqWEfC8TeDcwO75Gw" target="_u5qvsB2tEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wxRxkx2tEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wxRxlB2tEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wxRxkR2tEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wxRxkh2tEfC8TeDcwO75Gw" points="[-23, 12, -44, -173]$[-23, 180, -44, -5]$[20, 180, -1, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wxSYoB2tEfC8TeDcwO75Gw" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wxSYoR2tEfC8TeDcwO75Gw" id="(0.11627906976744186,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zUKlEB2tEfC8TeDcwO75Gw" type="4001" element="_zUJ-AB2tEfC8TeDcwO75Gw" source="_tVjWABqWEfC8TeDcwO75Gw" target="_u5qvsB2tEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zUKlEx2tEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zUKlFB2tEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zUKlER2tEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zUKlEh2tEfC8TeDcwO75Gw" points="[-63, 55, 172, -148]$[-63, 202, 172, -1]$[-215, 202, 20, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zULMIB2tEfC8TeDcwO75Gw" id="(1.0,0.367816091954023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0go_QB2tEfC8TeDcwO75Gw" type="4001" element="_0goYMB2tEfC8TeDcwO75Gw" source="_u5qvsB2tEfC8TeDcwO75Gw" target="_snUhkBqXEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0go_Qx2tEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0go_RB2tEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0go_QR2tEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0go_Qh2tEfC8TeDcwO75Gw" points="[-23, 11, -41, -602]$[-23, 570, -41, -43]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0gpmUB2tEfC8TeDcwO75Gw" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PKhn8x2uEfC8TeDcwO75Gw" type="4001" element="_PKhn8B2uEfC8TeDcwO75Gw" source="_PlatFhqhEfC8TeDcwO75Gw" target="_NFLsEB2uEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PKiPAB2uEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PKiPAR2uEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PKhn9B2uEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PKhn9R2uEfC8TeDcwO75Gw" points="[-80, -32, -452, 859]$[-80, -796, -452, 95]$[373, -796, 1, 95]$[373, -870, 1, 21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PKi2EB2uEfC8TeDcwO75Gw" id="(1.0,0.32989690721649484)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SDTy8B2uEfC8TeDcwO75Gw" type="4001" element="_SDPhgB2uEfC8TeDcwO75Gw" source="_V_o3IBqkEfC8TeDcwO75Gw" target="_NFLsEB2uEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SDTy8x2uEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SDTy9B2uEfC8TeDcwO75Gw" x="-16" y="-15"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SDTy8R2uEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SDTy8h2uEfC8TeDcwO75Gw" points="[-5, -2, -134, -69]$[125, -2, -4, -69]$[125, 50, -4, -17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SDUaAB2uEfC8TeDcwO75Gw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SmXcsh2uEfC8TeDcwO75Gw" type="4001" element="_SmW1oB2uEfC8TeDcwO75Gw" source="_NFLsEB2uEfC8TeDcwO75Gw" target="_kwZQVBqREfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SmYDwB2uEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SmYDwR2uEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SmXcsx2uEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SmXctB2uEfC8TeDcwO75Gw" points="[-7, -17, -154, 67]$[142, -17, -5, 67]$[142, -45, -5, 39]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SmZR4B2uEfC8TeDcwO75Gw" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qfMoIx2wEfC8TeDcwO75Gw" type="4001" element="_qfMoIB2wEfC8TeDcwO75Gw" source="_ejL8cBzcEfC8TeDcwO75Gw" target="_Bq63ABzkEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qfMoJh2wEfC8TeDcwO75Gw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qfMoJx2wEfC8TeDcwO75Gw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qfMoJB2wEfC8TeDcwO75Gw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qfMoJR2wEfC8TeDcwO75Gw" points="[0, 0, -647, 1437]$[648, -1434, 1, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qfN2QB2wEfC8TeDcwO75Gw" id="(1.0,0.39080459770114945)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qfN2QR2wEfC8TeDcwO75Gw" id="(0.5,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eYHq4B5bEfC_E-Cc_pi2TQ" type="4001" element="_eYGcwB5bEfC_E-Cc_pi2TQ" source="_FnelqRqTEfC8TeDcwO75Gw" target="_Q14F0BqVEfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eYHq4x5bEfC_E-Cc_pi2TQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eYHq5B5bEfC_E-Cc_pi2TQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eYHq4R5bEfC_E-Cc_pi2TQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eYHq4h5bEfC_E-Cc_pi2TQ" points="[-84, 54, 946, -421]$[-84, 87, 946, -388]$[-390, 87, 640, -388]$[-390, 227, 640, -248]$[-1030, 227, 0, -248]$[-1030, 431, 0, -44]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_eYJgEB5bEfC_E-Cc_pi2TQ" id="(1.0,0.35714285714285715)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uHvlcB5bEfC_E-Cc_pi2TQ" type="4001" element="_uHu-YB5bEfC_E-Cc_pi2TQ" source="_R0xxAB5ZEfC_E-Cc_pi2TQ" target="_m_phYB5bEfC_E-Cc_pi2TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uHvlcx5bEfC_E-Cc_pi2TQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uHvldB5bEfC_E-Cc_pi2TQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uHvlcR5bEfC_E-Cc_pi2TQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uHvlch5bEfC_E-Cc_pi2TQ" points="[0, 1, -48, 6]$[49, 10, 1, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uHxaoB5bEfC_E-Cc_pi2TQ" id="(1.0,0.32222222222222224)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vZlAwB5bEfC_E-Cc_pi2TQ" type="4001" element="_vZkZsB5bEfC_E-Cc_pi2TQ" source="_TsEX4B5bEfC_E-Cc_pi2TQ" target="_R0xxAB5ZEfC_E-Cc_pi2TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vZlAwx5bEfC_E-Cc_pi2TQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vZlAxB5bEfC_E-Cc_pi2TQ" x="2" y="21"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vZlAwR5bEfC_E-Cc_pi2TQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vZlAwh5bEfC_E-Cc_pi2TQ" points="[-14, 8, -126, -4]$[116, -21, 4, -33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vZm18B5bEfC_E-Cc_pi2TQ" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xBs1IB5bEfC_E-Cc_pi2TQ" type="4001" element="_xBeysB5bEfC_E-Cc_pi2TQ" source="_TsEX4B5bEfC_E-Cc_pi2TQ" target="_m_phYB5bEfC_E-Cc_pi2TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xBtcMB5bEfC_E-Cc_pi2TQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xBtcMR5bEfC_E-Cc_pi2TQ" x="-4" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xBs1IR5bEfC_E-Cc_pi2TQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xBs1Ih5bEfC_E-Cc_pi2TQ" points="[-23, -28, -418, -13]$[-23, -100, -418, -85]$[394, -100, -1, -85]$[394, -35, -1, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xBuqUB5bEfC_E-Cc_pi2TQ" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3g7iYB5bEfC_E-Cc_pi2TQ" type="4001" element="_3g67UB5bEfC_E-Cc_pi2TQ" source="_s-WHMBqnEfC8TeDcwO75Gw" target="_TsEX4B5bEfC_E-Cc_pi2TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3g7iYx5bEfC_E-Cc_pi2TQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3g7iZB5bEfC_E-Cc_pi2TQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3g7iYR5bEfC_E-Cc_pi2TQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3g7iYh5bEfC_E-Cc_pi2TQ" points="[0, 0, -129, 1895]$[401, 0, 272, 1895]$[401, -1564, 272, 331]$[164, -1564, 35, 331]$[164, -1816, 35, 79]$[129, -1816, 0, 79]$[129, -1873, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3g8wgB5bEfC_E-Cc_pi2TQ" id="(1.0,0.375)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7tj64B5bEfC_E-Cc_pi2TQ" type="4001" element="_7tiswB5bEfC_E-Cc_pi2TQ" source="_m_phYB5bEfC_E-Cc_pi2TQ" target="_UhQlgBzREfC8TeDcwO75Gw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7tj64x5bEfC_E-Cc_pi2TQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7tj65B5bEfC_E-Cc_pi2TQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7tj64R5bEfC_E-Cc_pi2TQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7tj64h5bEfC_E-Cc_pi2TQ" points="[-23, 11, 134, -236]$[-23, 128, 134, -119]$[-127, 128, 30, -119]$[-127, 200, 30, -47]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7tlJAB5bEfC_E-Cc_pi2TQ" id="(1.0,0.6976744186046512)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
