<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_t5pk4A9OEfCB18RrKNBr4g" name="MyDiagram1" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_t5pk4Q9OEfCB18RrKNBr4g" name="Pool1">
      <elements xmi:type="process:Lane" xmi:id="_t5pk4g9OEfCB18RrKNBr4g" name="Employee lane" actor="_t5pk-w9OEfCB18RrKNBr4g">
        <elements xmi:type="process:StartEvent" xmi:id="_t5pk4w9OEfCB18RrKNBr4g" name="client signup" outgoing="_7gNkYA9SEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t5pk5A9OEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t5pk5Q9OEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t5pk5g9OEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_4tTNUA9REfCB18RrKNBr4g" name="input all collected infomation into database system" outgoing="_N97SUA9SEfCB18RrKNBr4g" incoming="_79KmIA9SEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4tT0YQ9REfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4tT0YA9REfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4tT0Yg9REfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4tT0Yw9REfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4tT0ZA9REfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4tT0ZQ9REfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4tT0Zw9REfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4tT0Zg9REfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_G8UQwA9SEfCB18RrKNBr4g" name="perform risk assessment by KSC team" outgoing="_tTzJAA9SEfCB18RrKNBr4g" incoming="_N97SUA9SEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_G8U30A9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_G8UQwQ9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_G8U30Q9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_G8U30g9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_G8U30w9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_G8U31A9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_G8U31g9SEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_G8U31Q9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_YtxgMA9SEfCB18RrKNBr4g" name="client is not approved" incoming="_t6O24A9SEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YtxgMg9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YtxgMQ9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YtxgMw9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_r4wHUA9SEfCB18RrKNBr4g" name="client approval" outgoing="_t6O24A9SEfCB18RrKNBr4g _3PFGYA9SEfCB18RrKNBr4g" incoming="_tTzJAA9SEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r4wuYQ9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r4wuYA9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r4wuYg9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_0zemoA9SEfCB18RrKNBr4g" name="Set daily transaction limits" outgoing="_W-kW8A9TEfCB18RrKNBr4g" incoming="_3PFGYA9SEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0zemog9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0zemoQ9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0zemow9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0zempA9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0zempQ9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0zempg9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0zemqA9SEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0zempw9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_42JK0A9SEfCB18RrKNBr4g" name="gather client details " outgoing="_79KmIA9SEfCB18RrKNBr4g" incoming="_7gNkYA9SEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_42KY8Q9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_42KY8A9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_42KY8g9SEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_42KY8w9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_42KY9A9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_42KY9Q9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_42KY9w9SEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_42KY9g9SEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_SuHOYA9TEfCB18RrKNBr4g" name="Create a new client record in the &quot;Slipstream&quot;." outgoing="_dzSMAA9TEfCB18RrKNBr4g" incoming="_W-kW8A9TEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SuHOYg9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SuHOYQ9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SuHOYw9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SuHOZA9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SuHOZQ9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SuHOZg9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SuHOaA9TEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SuHOZw9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_c2fMkA9TEfCB18RrKNBr4g" name="assets" outgoing="_oR5f8A9TEfCB18RrKNBr4g _vNZScA9TEfCB18RrKNBr4g" incoming="_dzSMAA9TEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_c2gasQ9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_c2gasA9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_c2gasg9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_mRmcIA9TEfCB18RrKNBr4g" name="client not appoved" incoming="_oR5f8A9TEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mRnDMQ9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mRnDMA9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mRnDMg9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_pHx_EA9TEfCB18RrKNBr4g" name="Arrange face-to-face meeting between client and firm. " outgoing="_8ovdQA9TEfCB18RrKNBr4g" incoming="_vNZScA9TEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pHymIQ9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pHymIA9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pHymIg9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pHymIw9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pHymJA9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pHymJQ9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pHymJw9TEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pHymJg9TEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_8NgSwA9TEfCB18RrKNBr4g" name="onboarding process completed" incoming="_8ovdQA9TEfCB18RrKNBr4g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8NgSwg9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8NgSwQ9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8NgSww9TEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_t5pk9A9OEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_t5pk9Q9OEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_t5pk9g9OEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_t5pk9w9OEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N97SUA9SEfCB18RrKNBr4g" target="_G8UQwA9SEfCB18RrKNBr4g" source="_4tTNUA9REfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N975YA9SEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_N975YQ9SEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tTzJAA9SEfCB18RrKNBr4g" target="_r4wHUA9SEfCB18RrKNBr4g" source="_G8UQwA9SEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tTzwEA9SEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_tTzwEQ9SEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_t6O24A9SEfCB18RrKNBr4g" target="_YtxgMA9SEfCB18RrKNBr4g" source="_r4wHUA9SEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_t6O24Q9SEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_t6O24g9SEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3PFGYA9SEfCB18RrKNBr4g" target="_0zemoA9SEfCB18RrKNBr4g" source="_r4wHUA9SEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3PFGYQ9SEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_3PFGYg9SEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7gNkYA9SEfCB18RrKNBr4g" target="_42JK0A9SEfCB18RrKNBr4g" source="_t5pk4w9OEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7gNkYQ9SEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_7gNkYg9SEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_79KmIA9SEfCB18RrKNBr4g" target="_4tTNUA9REfCB18RrKNBr4g" source="_42JK0A9SEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_79KmIQ9SEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_79KmIg9SEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_W-kW8A9TEfCB18RrKNBr4g" target="_SuHOYA9TEfCB18RrKNBr4g" source="_0zemoA9SEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_W-k-AA9TEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_W-k-AQ9TEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dzSMAA9TEfCB18RrKNBr4g" target="_c2fMkA9TEfCB18RrKNBr4g" source="_SuHOYA9TEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dzSMAQ9TEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_dzSMAg9TEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oR5f8A9TEfCB18RrKNBr4g" target="_mRmcIA9TEfCB18RrKNBr4g" source="_c2fMkA9TEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oR5f8Q9TEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_oR5f8g9TEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vNZScA9TEfCB18RrKNBr4g" target="_pHx_EA9TEfCB18RrKNBr4g" source="_c2fMkA9TEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vNZScQ9TEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_vNZScg9TEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8ovdQA9TEfCB18RrKNBr4g" target="_8NgSwA9TEfCB18RrKNBr4g" source="_pHx_EA9TEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8ovdQQ9TEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_8ovdQg9TEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_t5pk-w9OEfCB18RrKNBr4g" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_t5pk_A9OEfCB18RrKNBr4g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_t5pk_Q9OEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_t5pk_g9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_t5pk_w9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_t5plAA9OEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_t5plAQ9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_t5plAg9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_t5plAw9OEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_t5plBA9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_t5plBQ9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_t5plBg9OEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_t5plBw9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_t5plCA9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_t5plCQ9OEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_t5plCg9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_t5plCw9OEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_ZXwJ8A9VEfCB18RrKNBr4g" name="Pool2">
      <elements xmi:type="process:StartEvent" xmi:id="_l3eaAA9VEfCB18RrKNBr4g" name="Client Initiates Broking Account Setup " outgoing="_rKvqcA9VEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_l3eaAg9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_l3eaAQ9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_l3eaAw9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_pntKYA9VEfCB18RrKNBr4g" name="create a booking account" outgoing="_yzkdAA9VEfCB18RrKNBr4g" incoming="_rKvqcA9VEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_pntKYg9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_pntKYQ9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_pntKYw9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_pntKZA9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_pntKZQ9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pntKZg9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_pntKaA9VEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_pntKZw9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_vp9nwA9VEfCB18RrKNBr4g" name="Client Deposits Funds via direct debit, cheque, or wire transfer " outgoing="_j5vFgA9WEfCB18RrKNBr4g" incoming="_yzkdAA9VEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_vp-O0Q9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_vp-O0A9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_vp-O0g9VEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_vp-O0w9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_vp-O1A9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vp-O1Q9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_vp-O1w9VEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_vp-O1g9VEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_jdcyIA9WEfCB18RrKNBr4g" name="Daily Transaction Limit Check" outgoing="_LXN8gA9XEfCB18RrKNBr4g _Lxs5EA9XEfCB18RrKNBr4g" incoming="_j5vFgA9WEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_jddZMQ9WEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_jddZMA9WEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_jddZMg9WEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_Je-BcA9XEfCB18RrKNBr4g" name="If transaction limit ≤ available funds, continue " outgoing="_bvB4cA9XEfCB18RrKNBr4g" incoming="_LXN8gA9XEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Je-ogQ9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Je-ogA9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Je-ogg9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_Je-ogw9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_Je-ohA9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Je-ohQ9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Je-ohw9XEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_Je-ohg9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_KKoNkA9XEfCB18RrKNBr4g" name="Re-review by KYC Risk Team&quot; " outgoing="_cZubQA9XEfCB18RrKNBr4g" incoming="_Lxs5EA9XEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_KKo0oQ9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_KKo0oA9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_KKo0og9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_KKo0ow9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_KKo0pA9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KKo0pQ9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_KKo0pw9XEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_KKo0pg9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_W8IKIA9XEfCB18RrKNBr4g" name="end process" incoming="_bvB4cA9XEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_W8IxMQ9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_W8IxMA9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_W8IxMg9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_YTrL4A9XEfCB18RrKNBr4g" name="end process " incoming="_cZubQA9XEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_YTry8Q9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_YTry8A9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_YTry8g9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ZXx_Lw9VEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZXx_MA9VEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ZXx_MQ9VEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZXx_Mg9VEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rKvqcA9VEfCB18RrKNBr4g" target="_pntKYA9VEfCB18RrKNBr4g" source="_l3eaAA9VEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rKvqcQ9VEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_rKvqcg9VEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yzkdAA9VEfCB18RrKNBr4g" target="_vp9nwA9VEfCB18RrKNBr4g" source="_pntKYA9VEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yzkdAQ9VEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_yzkdAg9VEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_j5vFgA9WEfCB18RrKNBr4g" target="_jdcyIA9WEfCB18RrKNBr4g" source="_vp9nwA9VEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_j5vFgQ9WEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_j5vskA9WEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LXN8gA9XEfCB18RrKNBr4g" target="_Je-BcA9XEfCB18RrKNBr4g" source="_jdcyIA9WEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LXN8gQ9XEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_LXN8gg9XEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Lxs5EA9XEfCB18RrKNBr4g" target="_KKoNkA9XEfCB18RrKNBr4g" source="_jdcyIA9WEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Lxs5EQ9XEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Lxs5Eg9XEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bvB4cA9XEfCB18RrKNBr4g" target="_W8IKIA9XEfCB18RrKNBr4g" source="_Je-BcA9XEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bvCfgA9XEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_bvCfgQ9XEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cZubQA9XEfCB18RrKNBr4g" target="_YTrL4A9XEfCB18RrKNBr4g" source="_KKoNkA9XEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cZvCUA9XEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_cZvCUQ9XEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_ZXx_Mw9VEfCB18RrKNBr4g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZXx_IA9VEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_ZXx_IQ9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZXx_Ig9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZXx_Iw9VEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_ZXx_JA9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZXx_JQ9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZXx_Jg9VEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_ZXx_Jw9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZXx_KA9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZXx_KQ9VEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_ZXx_Kg9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZXx_Kw9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZXx_LA9VEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_ZXx_LQ9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZXx_Lg9VEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_p0UYIA9XEfCB18RrKNBr4g" name="Pool3">
      <elements xmi:type="process:StartEvent" xmi:id="_rf2F0A9XEfCB18RrKNBr4g" name="client requests stock transfer" outgoing="_4bbygA9XEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_rf2s4Q9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_rf2s4A9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_rf2s4g9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_362N8A9XEfCB18RrKNBr4g" name="Issue Transfer Instruction Form&quot; " outgoing="_AOYKYA9YEfCB18RrKNBr4g" incoming="_4bbygA9XEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_362N8g9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_362N8Q9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_362N8w9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_362N9A9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_362N9Q9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_362N9g9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_362N-A9XEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_362N9w9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_80KtUA9XEfCB18RrKNBr4g" name="Complete Stock Migration&quot; " outgoing="_DxwKgA9YEfCB18RrKNBr4g" incoming="_AOYKYA9YEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_80KtUg9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_80KtUQ9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_80KtUw9XEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_80KtVA9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_80KtVQ9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_80KtVg9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_80KtWA9XEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_80KtVw9XEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_CK0B4A9YEfCB18RrKNBr4g" name="stock transfer complete" incoming="_DxwKgA9YEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_CK0B4g9YEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_CK0B4Q9YEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_CK0B4w9YEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_p0WNXw9XEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_p0WNYA9XEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_p0WNYQ9XEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_p0WNYg9XEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4bbygA9XEfCB18RrKNBr4g" target="_362N8A9XEfCB18RrKNBr4g" source="_rf2F0A9XEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4bbygQ9XEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_4bbygg9XEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AOYKYA9YEfCB18RrKNBr4g" target="_80KtUA9XEfCB18RrKNBr4g" source="_362N8A9XEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AOYKYQ9YEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_AOYKYg9YEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DxwKgA9YEfCB18RrKNBr4g" target="_CK0B4A9YEfCB18RrKNBr4g" source="_80KtUA9XEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DxwKgQ9YEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_DxwKgg9YEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_p0WNYw9XEfCB18RrKNBr4g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_p0WNUA9XEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_p0WNUQ9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_p0WNUg9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_p0WNUw9XEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_p0WNVA9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_p0WNVQ9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_p0WNVg9XEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_p0WNVw9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_p0WNWA9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_p0WNWQ9XEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_p0WNWg9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_p0WNWw9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_p0WNXA9XEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_p0WNXQ9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_p0WNXg9XEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_Z2HZkA9YEfCB18RrKNBr4g" name="Pool4">
      <elements xmi:type="process:StartEvent" xmi:id="_cIY-MA9YEfCB18RrKNBr4g" name="Client Ready for Trading Enablement" outgoing="_X2eAkA9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_cIY-Mg9YEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_cIY-MQ9YEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_cIY-Mw9YEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_NJkZAA9ZEfCB18RrKNBr4g" name=" &quot;Generate HIN&quot; " outgoing="_g74s8A9ZEfCB18RrKNBr4g" incoming="_YY5_QA9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_NJlAEQ9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_NJlAEA9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_NJlAEg9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_NJlAEw9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_NJlAFA9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NJlAFQ9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_NJlAFw9ZEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_NJlAFg9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_WsL-wA9ZEfCB18RrKNBr4g" name="HIN avability check" outgoing="_YY5_QA9ZEfCB18RrKNBr4g _dxIBIA9ZEfCB18RrKNBr4g" incoming="_X2eAkA9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_WsMl0Q9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_WsMl0A9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_WsMl0g9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_c4cFoA9ZEfCB18RrKNBr4g" name="Create Client Record in Slipstream&quot; " outgoing="_nPQvgA9ZEfCB18RrKNBr4g" incoming="_dxIBIA9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_c4cFog9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_c4cFoQ9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_c4cFow9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_c4cFpA9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_c4cssA9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_c4cssQ9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_c4cssw9ZEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_c4cssg9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_ftEwcA9ZEfCB18RrKNBr4g" name="end process" incoming="_g74s8A9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ftEwcg9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ftEwcQ9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ftFXgA9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_ibKuYA9ZEfCB18RrKNBr4g" name="enable client in trading website" outgoing="_r8f6sA9ZEfCB18RrKNBr4g" incoming="_nPQvgA9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ibKuYg9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ibKuYQ9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ibKuYw9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ibKuZA9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ibKuZQ9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ibKuZg9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ibKuaA9ZEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ibKuZw9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_qqmN8A9ZEfCB18RrKNBr4g" name="send welcome email" outgoing="_v_f2EA9ZEfCB18RrKNBr4g" incoming="_r8f6sA9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_qqm1AQ9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_qqm1AA9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_qqm1Ag9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_qqm1Aw9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_qqm1BA9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qqm1BQ9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_qqm1Bw9ZEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_qqm1Bg9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_qqm1CQ9ZEfCB18RrKNBr4g">
          <targetForm xmi:type="expression:Expression" xmi:id="_qqm1Cg9ZEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_qqm1CA9ZEfCB18RrKNBr4g"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_qqm1Cw9ZEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_udLuwA9ZEfCB18RrKNBr4g" name="trading enabled" incoming="_v_f2EA9ZEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_udMV0Q9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_udMV0A9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_udMV0g9ZEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Z2Invw9YEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_Z2InwA9YEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Z2InwQ9YEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_Z2Inwg9YEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_X2eAkA9ZEfCB18RrKNBr4g" target="_WsL-wA9ZEfCB18RrKNBr4g" source="_cIY-MA9YEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_X2eAkQ9ZEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_X2eAkg9ZEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YY5_QA9ZEfCB18RrKNBr4g" target="_NJkZAA9ZEfCB18RrKNBr4g" source="_WsL-wA9ZEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YY5_QQ9ZEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_YY5_Qg9ZEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dxIBIA9ZEfCB18RrKNBr4g" target="_c4cFoA9ZEfCB18RrKNBr4g" source="_WsL-wA9ZEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dxIBIQ9ZEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_dxIoMA9ZEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g74s8A9ZEfCB18RrKNBr4g" target="_ftEwcA9ZEfCB18RrKNBr4g" source="_NJkZAA9ZEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g74s8Q9ZEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_g74s8g9ZEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nPQvgA9ZEfCB18RrKNBr4g" target="_ibKuYA9ZEfCB18RrKNBr4g" source="_c4cFoA9ZEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nPQvgQ9ZEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_nPQvgg9ZEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r8f6sA9ZEfCB18RrKNBr4g" target="_qqmN8A9ZEfCB18RrKNBr4g" source="_ibKuYA9ZEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r8f6sQ9ZEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_r8f6sg9ZEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_v_f2EA9ZEfCB18RrKNBr4g" target="_udLuwA9ZEfCB18RrKNBr4g" source="_qqmN8A9ZEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_v_f2EQ9ZEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_v_f2Eg9ZEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_Z2Inww9YEfCB18RrKNBr4g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Z2InsA9YEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_Z2InsQ9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Z2Insg9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Z2Insw9YEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_Z2IntA9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Z2IntQ9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Z2Intg9YEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_Z2Intw9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Z2InuA9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Z2InuQ9YEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_Z2Inug9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Z2Inuw9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Z2InvA9YEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_Z2InvQ9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Z2Invg9YEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_E_HDkA9aEfCB18RrKNBr4g" name="Pool5">
      <elements xmi:type="process:StartEvent" xmi:id="_JaUqoA9aEfCB18RrKNBr4g" name="Process Monitoring Initiated" outgoing="_TAtWEA9aEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_JaVRsQ9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_JaVRsA9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_JaVRsg9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_RbWh0A9aEfCB18RrKNBr4g" name="check if process exceeds 30 days" outgoing="_cdlgMA9aEfCB18RrKNBr4g" incoming="_TAtWEA9aEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RbXI4Q9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RbXI4A9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RbXI4g9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_Y7CmgA9aEfCB18RrKNBr4g" name="Notify Head of Sales &amp; Head of Operations&quot; " outgoing="_gQAo8A9aEfCB18RrKNBr4g" incoming="_cdlgMA9aEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Y7DNkQ9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Y7DNkA9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Y7DNkg9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_Y7DNkw9aEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_Y7DNlA9aEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Y7DNlQ9aEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Y7DNlw9aEfCB18RrKNBr4g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_Y7DNlg9aEfCB18RrKNBr4g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_ecjHQA9aEfCB18RrKNBr4g" name="alert issued" incoming="_gQAo8A9aEfCB18RrKNBr4g">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ecjuUQ9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ecjuUA9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ecjuUg9aEfCB18RrKNBr4g" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_E_HDoA9aEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_E_HDoQ9aEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_E_HDog9aEfCB18RrKNBr4g">
        <targetForm xmi:type="expression:Expression" xmi:id="_E_HDow9aEfCB18RrKNBr4g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TAtWEA9aEfCB18RrKNBr4g" target="_RbWh0A9aEfCB18RrKNBr4g" source="_JaUqoA9aEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TAtWEQ9aEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_TAtWEg9aEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cdlgMA9aEfCB18RrKNBr4g" target="_Y7CmgA9aEfCB18RrKNBr4g" source="_RbWh0A9aEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cdlgMQ9aEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_cdlgMg9aEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gQAo8A9aEfCB18RrKNBr4g" target="_ecjHQA9aEfCB18RrKNBr4g" source="_Y7CmgA9aEfCB18RrKNBr4g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gQAo8Q9aEfCB18RrKNBr4g"/>
        <condition xmi:type="expression:Expression" xmi:id="_gQAo8g9aEfCB18RrKNBr4g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_E_HDpA9aEfCB18RrKNBr4g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E_HDkQ9aEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_E_HDkg9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E_HDkw9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E_HDlA9aEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_E_HDlQ9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E_HDlg9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E_HDlw9aEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_E_HDmA9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E_HDmQ9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E_HDmg9aEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_E_HDmw9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E_HDnA9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_E_HDnQ9aEfCB18RrKNBr4g">
        <name xmi:type="expression:Expression" xmi:id="_E_HDng9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_E_HDnw9aEfCB18RrKNBr4g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_t5plDA9OEfCB18RrKNBr4g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_t5plDQ9OEfCB18RrKNBr4g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_t5plDg9OEfCB18RrKNBr4g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_t5plDw9OEfCB18RrKNBr4g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_t5plEA9OEfCB18RrKNBr4g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_t5plEQ9OEfCB18RrKNBr4g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_t5plEg9OEfCB18RrKNBr4g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_t5plEw9OEfCB18RrKNBr4g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_t5plFA9OEfCB18RrKNBr4g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_t5plFQ9OEfCB18RrKNBr4g" type="Process" element="_t5pk4A9OEfCB18RrKNBr4g" name="MyDiagram1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_t5plFg9OEfCB18RrKNBr4g" type="2007" element="_t5pk4Q9OEfCB18RrKNBr4g">
      <children xmi:type="notation:DecorationNode" xmi:id="_t5plFw9OEfCB18RrKNBr4g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_t5plGA9OEfCB18RrKNBr4g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_t5plGQ9OEfCB18RrKNBr4g" type="3007" element="_t5pk4g9OEfCB18RrKNBr4g">
          <children xmi:type="notation:DecorationNode" xmi:id="_t5plGg9OEfCB18RrKNBr4g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_t5plGw9OEfCB18RrKNBr4g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_t5plHw9OEfCB18RrKNBr4g" type="3002" element="_t5pk4w9OEfCB18RrKNBr4g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_t5plIA9OEfCB18RrKNBr4g" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_t5plIQ9OEfCB18RrKNBr4g" x="9" y="32"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t5plIg9OEfCB18RrKNBr4g" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4tWQoA9REfCB18RrKNBr4g" type="3006" element="_4tTNUA9REfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4tWQog9REfCB18RrKNBr4g" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4tWQoQ9REfCB18RrKNBr4g" x="329" y="38" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_G8WF8A9SEfCB18RrKNBr4g" type="3006" element="_G8UQwA9SEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_G8WtAA9SEfCB18RrKNBr4g" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_G8WF8Q9SEfCB18RrKNBr4g" x="538" y="39" width="178" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YtyuUA9SEfCB18RrKNBr4g" type="3003" element="_YtxgMA9SEfCB18RrKNBr4g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_YtzVYA9SEfCB18RrKNBr4g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_YtzVYQ9SEfCB18RrKNBr4g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YtyuUQ9SEfCB18RrKNBr4g" x="861" y="26"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r4xVcA9SEfCB18RrKNBr4g" type="3009" element="_r4wHUA9SEfCB18RrKNBr4g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_r4x8gA9SEfCB18RrKNBr4g" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_r4x8gQ9SEfCB18RrKNBr4g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r4xVcQ9SEfCB18RrKNBr4g" x="775" y="152"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0zf0wA9SEfCB18RrKNBr4g" type="3006" element="_0zemoA9SEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0zf0wg9SEfCB18RrKNBr4g" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0zf0wQ9SEfCB18RrKNBr4g" x="889" y="123" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_42KY-A9SEfCB18RrKNBr4g" type="3006" element="_42JK0A9SEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_42LAAA9SEfCB18RrKNBr4g" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_42KY-Q9SEfCB18RrKNBr4g" x="134" y="42" width="166" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SuH1cA9TEfCB18RrKNBr4g" type="3006" element="_SuHOYA9TEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SuH1cg9TEfCB18RrKNBr4g" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SuH1cQ9TEfCB18RrKNBr4g" x="1108" y="121" width="188" height="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_c2hBwA9TEfCB18RrKNBr4g" type="3009" element="_c2fMkA9TEfCB18RrKNBr4g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_c2hBwg9TEfCB18RrKNBr4g" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_c2hBww9TEfCB18RrKNBr4g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_c2hBwQ9TEfCB18RrKNBr4g" x="1364" y="120"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mRnqQA9TEfCB18RrKNBr4g" type="3003" element="_mRmcIA9TEfCB18RrKNBr4g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_mRoRUA9TEfCB18RrKNBr4g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_mRoRUQ9TEfCB18RrKNBr4g" x="87" y="-15"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mRnqQQ9TEfCB18RrKNBr4g" x="1371" y="26"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pHzNMA9TEfCB18RrKNBr4g" type="3006" element="_pHx_EA9TEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pHzNMg9TEfCB18RrKNBr4g" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pHzNMQ9TEfCB18RrKNBr4g" x="1449" y="113" width="218" height="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8Ng50A9TEfCB18RrKNBr4g" type="3003" element="_8NgSwA9TEfCB18RrKNBr4g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8Ng50g9TEfCB18RrKNBr4g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8Ng50w9TEfCB18RrKNBr4g" x="20" y="23"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8Ng50Q9TEfCB18RrKNBr4g" x="1757" y="120"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_t5plIw9OEfCB18RrKNBr4g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_t5plJA9OEfCB18RrKNBr4g" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_t5plJQ9OEfCB18RrKNBr4g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_t5plJg9OEfCB18RrKNBr4g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t5plJw9OEfCB18RrKNBr4g" x="28" y="10" width="2342" height="335"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_t5plKA9OEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_t5plKQ9OEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_t5plKg9OEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_t5plKw9OEfCB18RrKNBr4g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t5plLA9OEfCB18RrKNBr4g" width="2370" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_ZX0bYA9VEfCB18RrKNBr4g" type="2007" element="_ZXwJ8A9VEfCB18RrKNBr4g">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZX0bZQ9VEfCB18RrKNBr4g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ZX0bZg9VEfCB18RrKNBr4g" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_l3fBEA9VEfCB18RrKNBr4g" type="3002" element="_l3eaAA9VEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_l3fBEg9VEfCB18RrKNBr4g" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_l3fBEw9VEfCB18RrKNBr4g" x="32" y="34"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l3fBEQ9VEfCB18RrKNBr4g" x="144" y="95"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_pnwNsA9VEfCB18RrKNBr4g" type="3006" element="_pntKYA9VEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_pnwNsg9VEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pnwNsQ9VEfCB18RrKNBr4g" x="312" y="44" width="189" height="95"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_vp-14A9VEfCB18RrKNBr4g" type="3006" element="_vp9nwA9VEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_vp_c8A9VEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vp-14Q9VEfCB18RrKNBr4g" x="552" y="44" width="205" height="102"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_jdeAQA9WEfCB18RrKNBr4g" type="3009" element="_jdcyIA9WEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_jdenUA9WEfCB18RrKNBr4g" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_jdenUQ9WEfCB18RrKNBr4g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jdeAQQ9WEfCB18RrKNBr4g" x="840" y="88"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Je_2oA9XEfCB18RrKNBr4g" type="3006" element="_Je-BcA9XEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_Je_2og9XEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Je_2oQ9XEfCB18RrKNBr4g" x="996" y="21" width="207" height="105"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_KKpbsA9XEfCB18RrKNBr4g" type="3006" element="_KKoNkA9XEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_KKpbsg9XEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KKpbsQ9XEfCB18RrKNBr4g" x="1002" y="167" width="196" height="98"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_W8JYQA9XEfCB18RrKNBr4g" type="3003" element="_W8IKIA9XEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_W8J_UA9XEfCB18RrKNBr4g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_W8J_UQ9XEfCB18RrKNBr4g" x="2" y="15"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_W8JYQQ9XEfCB18RrKNBr4g" x="1259" y="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_YTtBEA9XEfCB18RrKNBr4g" type="3003" element="_YTrL4A9XEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_YTtBEg9XEfCB18RrKNBr4g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_YTtBEw9XEfCB18RrKNBr4g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YTtBEQ9XEfCB18RrKNBr4g" x="1259" y="186"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZX0bYQ9VEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZX0bYg9VEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ZX0bYw9VEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ZX0bZw9VEfCB18RrKNBr4g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZX0bZA9VEfCB18RrKNBr4g" width="1405" height="325"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_p0XbcA9XEfCB18RrKNBr4g" type="2007" element="_p0UYIA9XEfCB18RrKNBr4g">
      <children xmi:type="notation:DecorationNode" xmi:id="_p0YCgA9XEfCB18RrKNBr4g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_p0YCgQ9XEfCB18RrKNBr4g" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_rf3T8A9XEfCB18RrKNBr4g" type="3002" element="_rf2F0A9XEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_rf3T8g9XEfCB18RrKNBr4g" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_rf3T8w9XEfCB18RrKNBr4g" x="23" y="38"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rf3T8Q9XEfCB18RrKNBr4g" x="120" y="110"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_362N-Q9XEfCB18RrKNBr4g" type="3006" element="_362N8A9XEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_362N-w9XEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_362N-g9XEfCB18RrKNBr4g" x="303" y="100" width="190" height="95"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_80KtWQ9XEfCB18RrKNBr4g" type="3006" element="_80KtUA9XEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_80KtWw9XEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_80KtWg9XEfCB18RrKNBr4g" x="570" y="96" width="190" height="95"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_CK0B5A9YEfCB18RrKNBr4g" type="3003" element="_CK0B4A9YEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_CK0B5g9YEfCB18RrKNBr4g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_CK0B5w9YEfCB18RrKNBr4g" x="-4" y="20"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CK0B5Q9YEfCB18RrKNBr4g" x="864" y="133"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_p0XbcQ9XEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_p0Xbcg9XEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_p0Xbcw9XEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_p0YCgg9XEfCB18RrKNBr4g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_p0XbdA9XEfCB18RrKNBr4g" width="1320" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Z2Kc4A9YEfCB18RrKNBr4g" type="2007" element="_Z2HZkA9YEfCB18RrKNBr4g">
      <children xmi:type="notation:DecorationNode" xmi:id="_Z2Kc5Q9YEfCB18RrKNBr4g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Z2Kc5g9YEfCB18RrKNBr4g" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_cIY-NA9YEfCB18RrKNBr4g" type="3002" element="_cIY-MA9YEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_cIY-Ng9YEfCB18RrKNBr4g" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_cIY-Nw9YEfCB18RrKNBr4g" x="42" y="37"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cIY-NQ9YEfCB18RrKNBr4g" x="144" y="110"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_NJmOMA9ZEfCB18RrKNBr4g" type="3006" element="_NJkZAA9ZEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_NJmOMg9ZEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NJmOMQ9ZEfCB18RrKNBr4g" x="504" y="36" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_WsNM4A9ZEfCB18RrKNBr4g" type="3009" element="_WsL-wA9ZEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_WsNz8A9ZEfCB18RrKNBr4g" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_WsNz8Q9ZEfCB18RrKNBr4g" x="12" y="12"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WsNM4Q9ZEfCB18RrKNBr4g" x="264" y="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_c4dTwA9ZEfCB18RrKNBr4g" type="3006" element="_c4cFoA9ZEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_c4dTwg9ZEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_c4dTwQ9ZEfCB18RrKNBr4g" x="504" y="156" width="182" height="91"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ftF-kA9ZEfCB18RrKNBr4g" type="3003" element="_ftEwcA9ZEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_ftF-kg9ZEfCB18RrKNBr4g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_ftF-kw9ZEfCB18RrKNBr4g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ftF-kQ9ZEfCB18RrKNBr4g" x="744" y="10"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ibLVcA9ZEfCB18RrKNBr4g" type="3006" element="_ibKuYA9ZEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_ibLVcg9ZEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ibLVcQ9ZEfCB18RrKNBr4g" x="744" y="155" width="186" height="94"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_qqncEA9ZEfCB18RrKNBr4g" type="3005" element="_qqmN8A9ZEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_qqoDIA9ZEfCB18RrKNBr4g" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qqncEQ9ZEfCB18RrKNBr4g" x="973" y="157" width="180" height="90"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_udM84A9ZEfCB18RrKNBr4g" type="3003" element="_udLuwA9ZEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_udM84g9ZEfCB18RrKNBr4g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_udM84w9ZEfCB18RrKNBr4g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_udM84Q9ZEfCB18RrKNBr4g" x="1224" y="176"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Z2Kc4Q9YEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Z2Kc4g9YEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Z2Kc4w9YEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Z2Kc5w9YEfCB18RrKNBr4g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Z2Kc5A9YEfCB18RrKNBr4g" width="1320" height="311"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_E_Jf0A9aEfCB18RrKNBr4g" type="2007" element="_E_HDkA9aEfCB18RrKNBr4g">
      <children xmi:type="notation:DecorationNode" xmi:id="_E_Jf1Q9aEfCB18RrKNBr4g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_E_Jf1g9aEfCB18RrKNBr4g" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_JaV4wA9aEfCB18RrKNBr4g" type="3002" element="_JaUqoA9aEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_JaV4wg9aEfCB18RrKNBr4g" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_JaV4ww9aEfCB18RrKNBr4g" x="61" y="22"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JaV4wQ9aEfCB18RrKNBr4g" x="117" y="113"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RbZlIA9aEfCB18RrKNBr4g" type="3017" element="_RbWh0A9aEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RbZlIg9aEfCB18RrKNBr4g" type="5032">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RbaMMA9aEfCB18RrKNBr4g" x="36" y="32"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RbZlIQ9aEfCB18RrKNBr4g" x="312" y="41"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Y7D0oA9aEfCB18RrKNBr4g" type="3006" element="_Y7CmgA9aEfCB18RrKNBr4g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_Y7EbsQ9aEfCB18RrKNBr4g" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y7EbsA9aEfCB18RrKNBr4g" x="535" y="31" width="205" height="103"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_eck8cA9aEfCB18RrKNBr4g" type="3003" element="_ecjHQA9aEfCB18RrKNBr4g" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_eck8cg9aEfCB18RrKNBr4g" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_eck8cw9aEfCB18RrKNBr4g" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eck8cQ9aEfCB18RrKNBr4g" x="864" y="89"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_E_Jf0Q9aEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_E_Jf0g9aEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_E_Jf0w9aEfCB18RrKNBr4g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_E_Jf1w9aEfCB18RrKNBr4g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E_Jf1A9aEfCB18RrKNBr4g" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_t5plLQ9OEfCB18RrKNBr4g"/>
    <edges xmi:type="notation:Connector" xmi:id="_N98gcA9SEfCB18RrKNBr4g" type="4001" element="_N97SUA9SEfCB18RrKNBr4g" source="_4tWQoA9REfCB18RrKNBr4g" target="_G8WF8A9SEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N98gcw9SEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N98gdA9SEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N98gcQ9SEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N98gcg9SEfCB18RrKNBr4g" points="[0, 1, -119, 0]$[108, -1, -11, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N9-VoA9SEfCB18RrKNBr4g" id="(1.0,0.32222222222222224)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N9-VoQ9SEfCB18RrKNBr4g" id="(0.06179775280898876,0.4157303370786517)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tT0-MA9SEfCB18RrKNBr4g" type="4001" element="_tTzJAA9SEfCB18RrKNBr4g" source="_G8WF8A9SEfCB18RrKNBr4g" target="_r4xVcA9SEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tT0-Mw9SEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tT0-NA9SEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tT0-MQ9SEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tT0-Mg9SEfCB18RrKNBr4g" points="[0, 0, -83, -38]$[75, 51, -8, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tT2zYA9SEfCB18RrKNBr4g" id="(1.0,0.3258426966292135)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_t6QFAA9SEfCB18RrKNBr4g" type="4001" element="_t6O24A9SEfCB18RrKNBr4g" source="_r4xVcA9SEfCB18RrKNBr4g" target="_YtyuUA9SEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_t6QsEA9SEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_t6QsEQ9SEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_t6QFAQ9SEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_t6QFAg9SEfCB18RrKNBr4g" points="[-12, -17, -59, 67]$[48, -80, 1, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_t6UWcA9SEfCB18RrKNBr4g" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_t6UWcQ9SEfCB18RrKNBr4g" id="(0.6,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3PFtcA9SEfCB18RrKNBr4g" type="4001" element="_3PFGYA9SEfCB18RrKNBr4g" source="_r4xVcA9SEfCB18RrKNBr4g" target="_0zf0wA9SEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3PGUgA9SEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3PGUgQ9SEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3PFtcQ9SEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3PFtcg9SEfCB18RrKNBr4g" points="[-9, -2, -116, -25]$[101, 21, -6, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3PHioA9SEfCB18RrKNBr4g" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3PHioQ9SEfCB18RrKNBr4g" id="(0.03333333333333333,0.28888888888888886)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7gOLcA9SEfCB18RrKNBr4g" type="4001" element="_7gNkYA9SEfCB18RrKNBr4g" source="_t5plHw9OEfCB18RrKNBr4g" target="_42KY-A9SEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7gOygA9SEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7gOygQ9SEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7gOLcQ9SEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7gOLcg9SEfCB18RrKNBr4g" points="[-1, -10, -81, -19]$[68, 8, -12, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7gROwA9SEfCB18RrKNBr4g" id="(1.0,0.9333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7gROwQ9SEfCB18RrKNBr4g" id="(0.07228915662650602,0.4819277108433735)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_79LNMA9SEfCB18RrKNBr4g" type="4001" element="_79KmIA9SEfCB18RrKNBr4g" source="_42KY-A9SEfCB18RrKNBr4g" target="_4tWQoA9REfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_79LNMw9SEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_79L0QA9SEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_79LNMQ9SEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_79LNMg9SEfCB18RrKNBr4g" points="[0, 0, -83, 12]$[50, -17, -33, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_79NpcA9SEfCB18RrKNBr4g" id="(1.0,0.3614457831325301)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_79NpcQ9SEfCB18RrKNBr4g" id="(0.18333333333333332,0.4222222222222222)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_W-k-Ag9TEfCB18RrKNBr4g" type="4001" element="_W-kW8A9TEfCB18RrKNBr4g" source="_0zf0wA9SEfCB18RrKNBr4g" target="_SuH1cA9TEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_W-llEA9TEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_W-llEQ9TEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_W-k-Aw9TEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_W-k-BA9TEfCB18RrKNBr4g" points="[0, -4, -92, 0]$[84, -6, -8, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_W-naQA9TEfCB18RrKNBr4g" id="(1.0,0.34444444444444444)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_W-naQQ9TEfCB18RrKNBr4g" id="(0.0425531914893617,0.3404255319148936)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dzSzEA9TEfCB18RrKNBr4g" type="4001" element="_dzSMAA9TEfCB18RrKNBr4g" source="_SuH1cA9TEfCB18RrKNBr4g" target="_c2hBwA9TEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dzSzEw9TEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dzSzFA9TEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dzSzEQ9TEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dzSzEg9TEfCB18RrKNBr4g" points="[-51, 66, 44, -45]$[-89, 127, 6, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dzUoQA9TEfCB18RrKNBr4g" id="(1.0,0.2978723404255319)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oR6HAA9TEfCB18RrKNBr4g" type="4001" element="_oR5f8A9TEfCB18RrKNBr4g" source="_c2hBwA9TEfCB18RrKNBr4g" target="_mRnqQA9TEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oR6HAw9TEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oR6HBA9TEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oR6HAQ9TEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oR6HAg9TEfCB18RrKNBr4g" points="[0, -9, 0, 111]$[2, -117, 2, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oR78MA9TEfCB18RrKNBr4g" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oR78MQ9TEfCB18RrKNBr4g" id="(0.7,0.7666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vNZ5gA9TEfCB18RrKNBr4g" type="4001" element="_vNZScA9TEfCB18RrKNBr4g" source="_c2hBwA9TEfCB18RrKNBr4g" target="_pHzNMA9TEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vNagkA9TEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vNagkQ9TEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vNZ5gQ9TEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vNZ5gg9TEfCB18RrKNBr4g" points="[-8, -2, -114, 0]$[101, -3, -5, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vNcVwA9TEfCB18RrKNBr4g" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vNcVwQ9TEfCB18RrKNBr4g" id="(0.022935779816513763,0.44954128440366975)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8owEUA9TEfCB18RrKNBr4g" type="4001" element="_8ovdQA9TEfCB18RrKNBr4g" source="_pHzNMA9TEfCB18RrKNBr4g" target="_8Ng50A9TEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8owrYA9TEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8owrYQ9TEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8owEUQ9TEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8owEUg9TEfCB18RrKNBr4g" points="[0, 0, -138, -28]$[132, 41, -6, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8oygkA9TEfCB18RrKNBr4g" id="(1.0,0.26605504587155965)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rKwRgA9VEfCB18RrKNBr4g" type="4001" element="_rKvqcA9VEfCB18RrKNBr4g" source="_l3fBEA9VEfCB18RrKNBr4g" target="_pnwNsA9VEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rKwRgw9VEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rKwRhA9VEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rKwRgQ9VEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rKwRgg9VEfCB18RrKNBr4g" points="[0, -16, -146, 2]$[138, -18, -8, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rKyGsA9VEfCB18RrKNBr4g" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rKyGsQ9VEfCB18RrKNBr4g" id="(0.06666666666666667,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yzlEEA9VEfCB18RrKNBr4g" type="4001" element="_yzkdAA9VEfCB18RrKNBr4g" source="_pnwNsA9VEfCB18RrKNBr4g" target="_vp-14A9VEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yzlrIA9VEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yzlrIQ9VEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yzlEEQ9VEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yzlEEg9VEfCB18RrKNBr4g" points="[0, 0, -93, -11]$[79, 9, -14, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yzngUA9VEfCB18RrKNBr4g" id="(1.0,0.3950617283950617)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yzngUQ9VEfCB18RrKNBr4g" id="(0.06829268292682927,0.4215686274509804)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j5wToA9WEfCB18RrKNBr4g" type="4001" element="_j5vFgA9WEfCB18RrKNBr4g" source="_vp-14A9VEfCB18RrKNBr4g" target="_jdeAQA9WEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j5wTow9WEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j5wTpA9WEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j5wToQ9WEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j5wTog9WEfCB18RrKNBr4g" points="[0, 0, -104, -35]$[83, 36, -21, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_j5yI0A9WEfCB18RrKNBr4g" id="(1.0,0.29411764705882354)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LXOjkA9XEfCB18RrKNBr4g" type="4001" element="_LXN8gA9XEfCB18RrKNBr4g" source="_jdeAQA9WEfCB18RrKNBr4g" target="_Je_2oA9XEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LXPKoA9XEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LXPKoQ9XEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LXOjkQ9XEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LXOjkg9XEfCB18RrKNBr4g" points="[-15, 5, -140, 51]$[125, -46, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LXQ_0A9XEfCB18RrKNBr4g" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LXQ_0Q9XEfCB18RrKNBr4g" id="(0.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LxtgIA9XEfCB18RrKNBr4g" type="4001" element="_Lxs5EA9XEfCB18RrKNBr4g" source="_jdeAQA9WEfCB18RrKNBr4g" target="_KKpbsA9XEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LxtgIw9XEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LxtgJA9XEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LxtgIQ9XEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LxtgIg9XEfCB18RrKNBr4g" points="[-7, -4, -143, -81]$[119, 79, -17, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LxvVUA9XEfCB18RrKNBr4g" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LxvVUQ9XEfCB18RrKNBr4g" id="(0.17,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bvCfgg9XEfCB18RrKNBr4g" type="4001" element="_bvB4cA9XEfCB18RrKNBr4g" source="_Je_2oA9XEfCB18RrKNBr4g" target="_W8JYQA9XEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bvCfhQ9XEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bvCfhg9XEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bvCfgw9XEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bvCfhA9XEfCB18RrKNBr4g" points="[0, 0, -46, -14]$[47, -1, 1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bvDtoA9XEfCB18RrKNBr4g" id="(1.0,0.3333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cZvpYA9XEfCB18RrKNBr4g" type="4001" element="_cZubQA9XEfCB18RrKNBr4g" source="_KKpbsA9XEfCB18RrKNBr4g" target="_YTtBEA9XEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cZvpYw9XEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cZvpZA9XEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cZvpYQ9XEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cZvpYg9XEfCB18RrKNBr4g" points="[0, 0, -63, -37]$[56, 23, -7, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cZw3gA9XEfCB18RrKNBr4g" id="(1.0,0.37142857142857144)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4bcZkA9XEfCB18RrKNBr4g" type="4001" element="_4bbygA9XEfCB18RrKNBr4g" source="_rf3T8A9XEfCB18RrKNBr4g" target="_362N-Q9XEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4bdAoA9XEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4bdAoQ9XEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4bcZkQ9XEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4bcZkg9XEfCB18RrKNBr4g" points="[0, -15, -163, -1]$[153, -14, -10, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4be10A9XEfCB18RrKNBr4g" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4be10Q9XEfCB18RrKNBr4g" id="(0.1,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AOYxcA9YEfCB18RrKNBr4g" type="4001" element="_AOYKYA9YEfCB18RrKNBr4g" source="_362N-Q9XEfCB18RrKNBr4g" target="_80KtWQ9XEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AOYxcw9YEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AOYxdA9YEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AOYxcQ9YEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AOYxcg9YEfCB18RrKNBr4g" points="[0, 0, -163, -19]$[138, 18, -25, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AOZ_kA9YEfCB18RrKNBr4g" id="(1.0,0.4142857142857143)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AOZ_kQ9YEfCB18RrKNBr4g" id="(0.16025641025641027,0.48717948717948717)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DxwxkA9YEfCB18RrKNBr4g" type="4001" element="_DxwKgA9YEfCB18RrKNBr4g" source="_80KtWQ9XEfCB18RrKNBr4g" target="_CK0B5A9YEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Dxwxkw9YEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DxwxlA9YEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DxwxkQ9YEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Dxwxkg9YEfCB18RrKNBr4g" points="[0, 21, -107, -1]$[104, 21, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Dxx_sA9YEfCB18RrKNBr4g" id="(1.0,0.34615384615384615)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Dxx_sQ9YEfCB18RrKNBr4g" id="(0.1,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_X2eAkw9ZEfCB18RrKNBr4g" type="4001" element="_X2eAkA9ZEfCB18RrKNBr4g" source="_cIY-NA9YEfCB18RrKNBr4g" target="_WsNM4A9ZEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_X2enoA9ZEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_X2enoQ9ZEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_X2eAlA9ZEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X2eAlQ9ZEfCB18RrKNBr4g" points="[-2, -23, -89, 47]$[79, -57, -8, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_X2gc0A9ZEfCB18RrKNBr4g" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YY6mUA9ZEfCB18RrKNBr4g" type="4001" element="_YY5_QA9ZEfCB18RrKNBr4g" source="_WsNM4A9ZEfCB18RrKNBr4g" target="_NJmOMA9ZEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YY7NYA9ZEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YY7NYQ9ZEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YY6mUQ9ZEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YY6mUg9ZEfCB18RrKNBr4g" points="[0, -7, -245, 0]$[221, -8, -24, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YY9CkA9ZEfCB18RrKNBr4g" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YY9CkQ9ZEfCB18RrKNBr4g" id="(0.17142857142857143,0.4857142857142857)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dxIoMQ9ZEfCB18RrKNBr4g" type="4001" element="_dxIBIA9ZEfCB18RrKNBr4g" source="_WsNM4A9ZEfCB18RrKNBr4g" target="_c4dTwA9ZEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dxIoNA9ZEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dxJPQA9ZEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dxIoMg9ZEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dxIoMw9ZEfCB18RrKNBr4g" points="[-6, -3, -233, -100]$[221, 96, -6, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dxLEcA9ZEfCB18RrKNBr4g" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dxLEcQ9ZEfCB18RrKNBr4g" id="(0.04285714285714286,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g75UAA9ZEfCB18RrKNBr4g" type="4001" element="_g74s8A9ZEfCB18RrKNBr4g" source="_NJmOMA9ZEfCB18RrKNBr4g" target="_ftF-kA9ZEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g75UAw9ZEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g75UBA9ZEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g75UAQ9ZEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g75UAg9ZEfCB18RrKNBr4g" points="[0, 0, -123, 36]$[127, -34, 4, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g757EA9ZEfCB18RrKNBr4g" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g76iIA9ZEfCB18RrKNBr4g" id="(0.7666666666666667,0.6666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nPRWkA9ZEfCB18RrKNBr4g" type="4001" element="_nPQvgA9ZEfCB18RrKNBr4g" source="_c4dTwA9ZEfCB18RrKNBr4g" target="_ibLVcA9ZEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nPRWkw9ZEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nPR9oA9ZEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nPRWkQ9ZEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nPRWkg9ZEfCB18RrKNBr4g" points="[0, 0, -114, -11]$[100, 10, -14, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nPTLwA9ZEfCB18RrKNBr4g" id="(1.0,0.4857142857142857)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nPTLwQ9ZEfCB18RrKNBr4g" id="(0.0915032679738562,0.45454545454545453)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r8hI0A9ZEfCB18RrKNBr4g" type="4001" element="_r8f6sA9ZEfCB18RrKNBr4g" source="_ibLVcA9ZEfCB18RrKNBr4g" target="_qqncEA9ZEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r8hI0w9ZEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r8hI1A9ZEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r8hI0Q9ZEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r8hI0g9ZEfCB18RrKNBr4g" points="[0, -7, -92, 0]$[76, -10, -16, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r8iW8A9ZEfCB18RrKNBr4g" id="(1.0,0.36363636363636365)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r8iW8Q9ZEfCB18RrKNBr4g" id="(0.16,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_v_gdIA9ZEfCB18RrKNBr4g" type="4001" element="_v_f2EA9ZEfCB18RrKNBr4g" source="_qqncEA9ZEfCB18RrKNBr4g" target="_udM84A9ZEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_v_gdIw9ZEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_v_gdJA9ZEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_v_gdIQ9ZEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_v_gdIg9ZEfCB18RrKNBr4g" points="[0, 0, -86, 10]$[71, -10, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_v_hEMA9ZEfCB18RrKNBr4g" id="(1.0,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TAt9IA9aEfCB18RrKNBr4g" type="4001" element="_TAtWEA9aEfCB18RrKNBr4g" source="_JaV4wA9aEfCB18RrKNBr4g" target="_RbZlIA9aEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TAt9Iw9aEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TAt9JA9aEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TAt9IQ9aEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TAt9Ig9aEfCB18RrKNBr4g" points="[0, -15, -134, 2]$[129, -17, -5, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TAvLQA9aEfCB18RrKNBr4g" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TAvLQQ9aEfCB18RrKNBr4g" id="(0.16666666666666666,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cdmHQA9aEfCB18RrKNBr4g" type="4001" element="_cdlgMA9aEfCB18RrKNBr4g" source="_RbZlIA9aEfCB18RrKNBr4g" target="_Y7D0oA9aEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cdmHQw9aEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cdmHRA9aEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cdmHQQ9aEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cdmHQg9aEfCB18RrKNBr4g" points="[-9, -1, -217, 0]$[193, -1, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cdn8cA9aEfCB18RrKNBr4g" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cdn8cQ9aEfCB18RrKNBr4g" id="(0.10714285714285714,0.5428571428571428)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gQBQAA9aEfCB18RrKNBr4g" type="4001" element="_gQAo8A9aEfCB18RrKNBr4g" source="_Y7D0oA9aEfCB18RrKNBr4g" target="_eck8cA9aEfCB18RrKNBr4g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gQBQAw9aEfCB18RrKNBr4g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gQBQBA9aEfCB18RrKNBr4g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gQBQAQ9aEfCB18RrKNBr4g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gQBQAg9aEfCB18RrKNBr4g" points="[0, 0, -139, -46]$[137, 31, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gQDFMA9aEfCB18RrKNBr4g" id="(1.0,0.2621359223300971)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
